ARM-software/workload-automation

wlauto/common/linux/device.py
wlauto/devices/linux/chromeos_test_image/__init__.py
wlauto/instrumentation/energy_model/__init__.py

I have implemented the changes proposed from the review,
thanks.

Pull request: second pull request for first batch of changes

---

wlauto/instrumentation/energy_model/__init__.py

Hi, 
this is the second batch of changes to make energy model work for chromeos test image device

Pull request: second batch of changes

---

wlauto/instrumentation/energy_model/__init__.py

After doing some cleaning up and adding the validation bit we discussed this is my pull request for the
thermal adjustment feature of energy model.

Energy model instruments: allows power adjustment for thermal effect

---

wlauto/workloads/rt_app/use_cases/spreading-tasks.json
wlauto/workloads/rt_app/use_cases/video-long.json
wlauto/workloads/rt_app/use_cases/video-short.json

Add video-long.json and video-short.json files and update spreading-tasks.json. The originals can be
found in git.linaro.org/power/rt-app.git repo.

rt-app: Update use cases

---

wlauto/utils/ssh.py

- Added port kwarg to telnet login function (default port=23)

Fixed telnet support

---

wlauto/common/android/device.py
wlauto/devices/android/gem5/__init__.py
wlauto/utils/ssh.py

Added the Gem5Device to WA.
As part of this, also enabled password-less telnet connections.

Add Gem5Device to WA

---

wlauto/instrumentation/daq/__init__.py

If the parameter merge_channels is set to true (false by default).
DAQ channels that have consecutive letters on the end of their names
will be summed together. E.g: A7, A15a, A15b becomes A7, A15
You can also  manually specify a channel mapping by setting
merge_channels to a dict. .

Added ability to merge DAQ channels

---

wlauto/instrumentation/freqsweep/__init__.py

Added an instrument to sweep a workload across all available frequenices
for both big and little cores

Added freqsweep instrument

---

doc/source/changes.rst

Initial update of change log, this will probably need a lot of tidy up.

Updated change log

---

doc/source/installation.rst
doc/source/quickstart.rst

Re-writing some of the instructions for clarity plus updating with the
correct pip invocations.

doc: updating installation instructions

---

wlauto/instrumentation/systrace/__init__.py

Added an instrument to uses systrace.py from the android SDK.
Generates a fancy HTML report (only works in Google chrome).

Added systrace instrument

---

wlauto/workloads/hwuitest/__init__.py

This workload allow WA to use hwuitest from AOSP to test rendering
latency on Android devices.

hwuitest: Added workload

---

wlauto/common/android/device.py
wlauto/workloads/recentfling/__init__.py

Added recent fling and fixed swipe_to_unlock

Recentfling

---

wlauto/instrumentation/juno_energy/__init__.py

- Summary metrics are now calculated from the contents of energy.csv and
added to the overall results.
- Added a new "strict" parameter. If this is set to False, the device
check during validation is omitted.

juno_energy: add metrics to results and "strict" parameter

---

wlauto/utils/trace_cmd.py

Updated trace-cmd parser to handle messages that the trace for a CPU is
empty.

trace_cmd: updated to handle empty CPUs.

---

wlauto/workloads/apklaunch/__init__.py

This is a workload to install and run an arbitrary .apk

workloads: Add apklaunch workload

---

wlauto/workloads/bbench/__init__.py
wlauto/workloads/bbench/patches/bbc.html
wlauto/workloads/bbench/patches/cnn.html
wlauto/workloads/bbench/patches/twitter.html
wlauto/workloads/recentfling/__init__.py

Fix for web browser crash on latest Linaro release
Also fixes browser permissions issues on Android 6+ and recentfling version check.

bbench fix

---

wlauto/core/bootstrap.py
wlauto/managers/locallinux.py

This allows WA to automate the machine it is running on.

LocalLinuxManager: Added a local linux manager

---

wlauto/instrumentation/freqsweep/__init__.py

- Added explanation that this instrument does not taskset workloads
- Fixed formatting issue with the agenda example

freq_sweep: Improved documentation

---

wlauto/utils/android.py

As of android N '\n' is used as the new line separator not '\r\n'.
This fix makes the function detect which is being used by the device.

adb_shell: Fixed checking exit codes on Android N

---

wlauto/workloads/lmbench/__init__.py

This patch tidies up the benchmark code to bring it in line with the
style used in Workload Automation in general. Additionally, the
results from sub-benchmarks are now directly written to a file on the
device as opposed to processing the standard output/error from the
benchmark, which was error prone.

lmbench: Tidied up the code and improved stability

---

wlauto/utils/android.py
wlauto/utils/misc.py

As of ADB 1.0.35/Android N, it will return the exit code of the command that it runs
This code handles this scenario as before WA treated a return code from ADB as an
error with ADB.

ADB 1.0.35 support

---

wlauto/workloads/glbcorp/__init__.py

The old results looked like:
I/TfwActivity(30824):    "description": "",
I/TfwActivity(30824):    "elapsed_time": 62070,
I/TfwActivity(30824):    "error": "NOERROR",
The new format is:
04-04 11:38:04.144  1410  1410 I TfwActivity:    "description": "",
04-04 11:38:04.144  1410  1410 I TfwActivity:    "elapsed_time": 62009,
04-04 11:38:04.144  1410  1410 I TfwActivity:    "error": "NOERROR",

glbench: Fixed updated logcat format

---

wlauto/instrumentation/fps/__init__.py

Previously fps only captured a single 'view' attribute given to it by the workload.
This change allows you to pass a list of 'views' and the latency command will be run for every view in the list - if that view is currently visible.

fps: Can now process multiple 'view' attributes

---

wlauto/core/bootstrap.py

- handle ValueError as well as SyntaxError from config parser
- Report source file in the error message

boostrap: nicer error messages on config parasing.

---

wlauto/common/android/workload.py

It's possible that there is already a version of an app on target that
differs form the version of the apk on the host. In such cases, WA will
usually try to uninstall the target version and install the host
version.
It's possible that the uninstall may fail. If that happens, it will be
reported as a warning but workload exectuion will proceed with the
target version. In this case, apk_version would have already been set to
that of the host apk. This change ensures that the APK version is
correctly set to the target version (the one that actually ran).

ApkWorkload: report correct apk verison on failed install

---

wlauto/common/android/device.py
wlauto/devices/android/gem5/__init__.py
wlauto/instrumentation/hwmon/__init__.py
wlauto/utils/android.py
wlauto/utils/hwmon.py

Fixes:
- hwmon sensor naming
- getting exit codes from commands run via adb

hwmon & adb fixes

---

wlauto/common/android/device.py

These are now gathered via `getprop` rather than trying to parse the
build.prop file directly.
This fixes issues with build.prop files that have imports.

AndroidDevice: Improved gathering of build props

---

wlauto/workloads/cameracapture/__init__.py
wlauto/workloads/camerarecord/__init__.py

Parameters were not being passed to the UI automation properly

cameracapture & camerarecord: Fixed parameters

---

wlauto/instrumentation/servo_power_monitors/__init__.py
wlauto/utils/cros_sdk.py

Servo is a debug board used for Chromium OS test and development. Among other uses, it allows
access to the built in power monitors (if present) of a Chrome OS device. More information on
Servo board can be found in the link bellow:
https://www.chromium.org/chromium-os/servo
based on: https://github.com/vflouris/workload-automation/commit/03ede10739add543251b7827621370e647878a26
and: https://github.com/freedomtan/workload-automation/commit/9a0dc55b55fa7a806703a1a43901ea91f14c2e6a

servo_power: Added support for chromebook servo boards

---

wlauto/instrumentation/netstats/__init__.py
wlauto/instrumentation/servo_power_monitors/__init__.py

Now checks to see if the device is running chromeOS.

servo_power: Added check for device platform.

---

doc/source/changes.rst
doc/source/installation.rst
doc/source/invocation.rst
doc/source/revent.rst
wlauto/instrumentation/misc/__init__.py
wlauto/workloads/facebook/__init__.py
wlauto/workloads/recentfling/__init__.py

- Added 2.5.0 Change log
- Updated Revent documentation
- Removed apk_version instrument

Documentation changes & Removing apk_version

---

wlauto/workloads/camerarecord/__init__.py

Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>

camerarecord: add frame stats collection through dumpsys gfxinfo

---

wlauto/workloads/camerarecord/__init__.py
wlauto/workloads/camerarecord/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java

Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>

camerarecord: add possibility to select slow_motion recording mode

---

wlauto/instrumentation/fps/__init__.py
wlauto/result_processors/uxperf.py
wlauto/utils/fps.py

Includes :
- Fix for FpsProcessor logic when data for filtered_vsyncs_to_compose is empty
- Adds dumpsys_period parameter for controlling the frequency of dumpsys in the fps instrument
- New logging calls and exception handling in uxperf result processor.

Additional changes to FpsProcessor, fps instrument and uxperf result processor

---

wlauto/common/android/workload.py

This method is no longer used nor needed as runtime permissions for API 23 and above are now granted on `adb install` using the `-g` flag — see https://github.com/ARM-software/workload-automation/commit/fab6a977aa8e936b504b41da480f2de10310dc90
After a recent update on some Android 6.0.x devices (eg. Huawei Mate 8 and Nexus 5X), it may even cause WA to fail with a security error when trying to grant permissions that were already allowed during `adb install -g`.

Remove unused method - permission grant for API 23 and above

---

wlauto/commands/get-assets.py

Reimplemented, as per conversation on #206

Add script to get external assets for workloads

---

wlauto/__init__.py
wlauto/common/android/workload.py

Create a new workload class to encapsulate functionality common to all
uxperf workloads.

Add new AndroidUxPerfWorkload class

---

wlauto/common/android/workload.py

Changes to the AndroidUxPerfWorkload class.
- Move parameters from setup() to validate()
- Add package name to parameter list

Android uxperf workload

---

doc/source/revent.rst
wlauto/commands/record.py
wlauto/common/android/workload.py
wlauto/utils/statedetect.py

ReventWorkload: Added argument to take screen capture with revent record command
ReventWorkload: State detection fixes

ReventWorkload

---

wlauto/utils/android.py

When using 'check_exit_code' and 'as_root' options for adb_shell with
a command containing single quotes, the provided command was escaped
twice which has now been avoided.

android: Fixed issue using single quoted command with adb_shell

---

wlauto/utils/statedetect.py

Due to inaccuracies in revent playback, the resultant state does not
always match the templates precisely causing state detection to fail.
To help this images are now scaled to different sizes before being
matched to the templates to compensate for slight variations in size.

ReventWorkload: Modified statedection to vary scale of images

---

wlauto/instrumentation/fps/__init__.py
wlauto/utils/fps.py

Auto detects and uses appropriate method via android version of device.
Output 90th, 95th and 99th percentile metrics. This happens for both SurfaceFlinger and Gfxinfo methods.

FPS. Added gfxinfo methods of obtaining fps stats.

---

wlauto/workloads/rt_app/use_cases/camera-long.json
wlauto/workloads/rt_app/use_cases/camera-short.json

Add camera-long.json and camera-short.json files to simulate camera
recorder.
Signed-off-by: Leo Yan <leo.yan@linaro.org>

rt-app: add user case for camera

---

wlauto/workloads/adobereader/__init__.py

Change min apk ver for reader

---

wlauto/utils/fps.py

Fixed: if index isnt zero based, drop(0) will fail

FPS percentiles: Ignore ValueError when NaN

---

wlauto/workloads/octaned8/__init__.py

A workload to run the binary (non-browser) version of Octane

Add Octane d8 workload

---

wlauto/workloads/octaned8/__init__.py

Ensure the device log file is deleted between runs and that the host file is not kept as an
artefact.  Both can lead to errors appending data from the next iteration/run.

Fix octaned8 results capture

---

wlauto/tests/test_exec_control.py
wlauto/utils/exec_control.py

Added 3 decorators to enabled methods to be executed conditionally:
- Once for each method instance.
- Once for each class.
- Only once per environment including any derived classes.
Added execution control allowing for different environments to
be used in order to determine how often decorated commands should be ran.
Added relevant unittests for the above decorators.

Decorators: Added initial version of decorators and environment manager

---

doc/source/apk_workloads.rst
wlauto/common/android/device.py
wlauto/common/android/workload.py
wlauto/common/linux/device.py
wlauto/resource_getters/standard.py
wlauto/utils/android.py
wlauto/utils/misc.py
wlauto/workloads/dex2oat/__init__.py

Modified how apks containing native code are matched to a target devices supported abi(s).

Modified how apks containing native code are matched to a target devices supported abi(s).

---

wlauto/workloads/adobereader/__init__.py
wlauto/workloads/gmail/__init__.py
wlauto/workloads/googlephotos/__init__.py
wlauto/workloads/googleplaybooks/__init__.py
wlauto/workloads/googleslides/__init__.py
wlauto/workloads/skype/__init__.py
wlauto/workloads/youtube/__init__.py

The known working version is now part of the description instead

Removed min_apk_version from UXperf workloads

---

wa/framework/configuration/core.py
wa/framework/configuration/parsers.py
wa/framework/configuration/plugin_cache.py
wa/framework/target/descriptor.py
wa/framework/target/info.py
wa/framework/target/manager.py
wa/utils/log.py

Due to an unfortunate rebase, the previous pull request submitted changes
reverting updates to target instantiation mechanism along with a minor log fix.
This commit re-reverts the changes to the former and re-submits the latter in a
separte commit.

Fixing previous pull request.

---

wa/framework/job.py
wa/framework/target/assistant.py
wa/framework/target/manager.py
wa/framework/target/runtime_config.py
wa/framework/target/runtime_parameter_manager.py
wa/tests/test_runtime_param_utils.py
wa/utils/misc.py

TM has been updated and restructured to be clearer, including splitting off
assistant and creating a runtime parameter manager in their own files.

TM: Update and Refactor

---

wa/framework/configuration/plugin_cache.py
wa/framework/plugin.py
wa/instrumentation/trace-cmd.py

This pull request relies on the following devlib commits:
https://github.com/ARM-software/devlib/commit/7e80a381d8ffeb6282d476b9956d6a3d8fa63a04
https://github.com/ARM-software/devlib/commit/61b13383a4e5edbd7d369e149d3cf4d637a622c0
https://github.com/ARM-software/devlib/commit/92d9e690f03ad14279882fa8b5e7949fd36a36c9

Add trace-cmd instrument

---

wa/framework/execution.py
wa/workloads/idle.py

This depends on https://github.com/ARM-software/devlib/commit/69a83d4128c9395a5cb1f9c11ad63a75c3787a95

Add idle workload

---

wlauto/utils/ssh.py

This back-ports ssh_get_shell implementation from devlib. It includes
the following changes:
- original_prompt for Telnet verison of the connection can now be passed
as an argument.
- Multiple attempts to connect with a timeout.
- Some additional implementation to the tty, including setting the size.

ssh: Back-port ssh_get_shell from devlib

---

wlauto/instrumentation/misc/__init__.py

Previously due to WA automagic the initialization method would only be
called once globally, meaning that it was called for cpufreq extraction
but not for sysfiles. This commit splits SysfsExtractor into a base
FsExtractor and a SysfsExtractor subclass and the initialization methods
are explicitly called by both children.

Instrumentation: Fixes SysfsExtractor with tmpfs

---

wa/framework/getters.py
wa/framework/resource.py
wa/framework/workload.py

Dependant on https://github.com/ARM-software/devlib/pull/150

Apk resolution

---

wlauto/utils/trace_cmd.py

': ' is used as the delimiter for the different parts of of the event
line; unfortunately, it is also a valid character sequence to appear in
a task name.
This change attempts to perform the event line split correctly by
ensuring that the cpu id is present in the first part.

utils/trace_cmd: expect ': ' in task name

---

wlauto/common/gem5/device.py

Changed "self.longdelay" to "self.long_delay".

gem5: fixed a typo

---

tests/test_utils.py
wa/framework/configuration/core.py
wa/framework/instrumentation.py
wa/utils/misc.py
wa/utils/types.py

Make enum more conceptually consistent and robust, and add tests to document its usage.

Enum enhancements.

---

wa/instrumentation/energy_measurement.py

Dependant on PR https://github.com/ARM-software/devlib/pull/163

Energy measurement

---

wlauto/utils/ssh.py

This fixes the ability to connect over telnet rather than SSH which was
broken by commit 51db53d9
ssh: Back-port ssh_get_shell from devlib

utils/ssh: fix telnet connection

---

wa/workloads/homescreen/__init__.py

Just did:  wlauto      -> wa
self.device -> self.target

Homescreen: Port homescreen workload to WA3

---

wa/framework/workload.py
wa/instrumentation/fps.py

This depends on this devlib pull request: https://github.com/ARM-software/devlib/pull/179

Add FPS instrument

---

wa/framework/configuration/plugin_cache.py
wa/framework/target/descriptor.py

- Fix some whitespace (my editor does this automatically and I'm too lazy to change it, if you prefer I ignore it I can stop submitting these fixes every time I touch a file...)
- Fix a typo and clarify a description string
- Improve the error message for a certain type of invalid configuration

Misc clarifications/cleanups

---

wa/instrumentation/energy_measurement.py

Sorry, this one got a little crazy.. I promise this is my best effort at a simple & concise solution!
=======
Devlib's ACME instrument uses iio-capture under the hood, which can
only capture data from one IIO device at a time. Devlib's instrument
API expects to produce a single CSV file for the Instrument, with a
single axis of sample timestamps. These two things cannot be
correctly reconciled without changing the devlib Instrument API -
get_data would need to be able to return two distinct sets of data.
Instead, where required WA will instantiate the ACME instrument
multiple times (once for each IIO device), producing two separate CSV
files. Aggregated energy info (as opposed to timestamped samples of
energy data) _can_ be meaningfully combined from multiple IIO
devices, so the derived …

energy_measurement: Allow multiple IIO devices for ACME

---

wa/instrumentation/energy_measurement.py

Typo'd this and seems I failed to test it

Fixup standard energy channels fix

---

wa/instrumentation/dmesg.py

Maybe this belongs in devlib? It's pretty trivial so fine here IMO.

WA3 dmesg instrument

---

wa/framework/execution.py
wa/framework/instrumentation.py
wa/framework/job.py
wa/framework/processor.py
wa/utils/log.py

This adds error- and warning-level messages from selected loggers to the output events.

Logger events

---

wa/framework/target/runtime_config.py
wa/framework/workload.py
wa/workloads/geekbench/__init__.py

Depends on https://github.com/ARM-software/devlib/pull/193

Add Workload.requires_network

---

wa/workloads/geekbench/__init__.py

I really don't understand why this has been working up until now.. but it stopped working and this is definitely needed :confused:

Geekbench fixes

---

wa/processors/csvproc.py

We currently populate results_so_far with a JobOutput for each Job and then a
Result for the RunOutput. This results in a bug when trying to access the
id/label/iteration.
This is fixed by always ensuring the we store Output objects and not
Results (results_so_far is renamed to outputs_so_far to reflect this), and
treating the RunOutput specially in _write_outputs.

Csvproc fix

---

wa/framework/entrypoint.py

In order to properly enable verbose logging for plugin enumeration,
verbosity option must be extracted before commands are processed, and
therefore before all valid arguments are known.
ArgumentParser.parse_known_args() is used for this, which will collect
all unexpected arguments into an "extras" list, rather than raising an
error. This, however, has an outstanding bug, where if say option '-v'
is known and '-f is unknown, args '-v -f' will be parsed correctly (with
'-f' being collected into extras), but '-vf' will not, resulting in an
error.
To get around this, pre-process sys.argv to detect joined options and
manually split them into separate args.

framework/entrypoint: fix joined options parsing.

---

wa/framework/workload.py

Mandate that either a package name is specified or the owner defines
supported package names for use during package resolution.

Fix package resolution

---

wa/framework/configuration/execution.py

This reverts commit 7a3503775d77ba7658a782908b2376af64d87e39.

Revert "DO NOT MERGE: stub out broken method"

---

wa/commands/revent.py

Update revent commands to supply output directory when creating
TargetManager and fix ignoring any additional device config provided.

commands/revent: Fix revent command

---

wa/processors/targz.py

Add an output processor to create a tarball of WA output directory.

processors: add targz processor

---

wa/framework/target/descriptor.py
wa/instrumentation/energy_measurement.py

NOTE: this pull request depends on https://github.com/ARM-software/devlib/pull/220

Juno fixes.

---

wa/commands/show.py
wa/framework/target/descriptor.py
wa/framework/workload.py
wa/utils/doc.py

Show Command

---

wa/framework/target/assistant.py

If the target is rooted, attempt to disable selinux as this can cause
issues during runtime.

Target/AndroidAssistant: Try to disable selinux

---

wa/utils/revent.py

Changed location of revent binary on target to be a class attribute so that
it is shared across all instances. Also changed discovery method to a
static method which can be memoized to prevent the target being queried
unnecessarily.

utils/revent: Refactor ReventRecording to avoid duplicate target calls

---

wa/workloads/shellscript/__init__.py

Port shellscript workload that allows running an arbitrary shellscript
as a WA workload from WA2.

workloads: port shellscript workload from WA2

---

wa/framework/target/assistant.py
wa/framework/target/descriptor.py
wa/framework/target/runtime_config.py
wa/framework/workload.py

Dependant on PR-https://github.com/ARM-software/devlib/pull/228

[RFC] Add Initial Support for ChromeOs

---

wa/workloads/the_chase/__init__.py

Updated default view to run on Android N

workloads/thechase: Port workload to WA3

---

wa/workloads/exoplayer/__init__.py

Add view for th workload, so that SurfaceFlinger frame data can be
collected for it.

workloads/exoplayer: add view

---

wa/workloads/hackbench/__init__.py

- Only install/uninstall the executable once per run
- Add results file as a raw artifact

workloads/hackbench: fixes

---

extras/README

Update README to contain information about the Dockerfile and
re-wrapped to 80 characters.

extras: Update README & reflow

---

wa/workloads/jankbench/__init__.py

Add automation for Google's jankbench workload.

workloads: add jankbench

---

wa/workloads/hwuitest/__init__.py

Port automation for hwuitest (Android's libhwui microbenchmark) from
WA2.

workloads: add hwuitest

---

wa/workloads/geekbench/__init__.py

Add missing newline to description in order to display correctly in
the show command and remove extra spaces.

workloads/geekbench: Fix formatting

---

wa/framework/configuration/plugin_cache.py

Add plugin type-specific methods (e.g. get_workload()) to plugin cache
so that it exposes the same interface as plugin loader.

fw/config: add plugin type methods to plugin_cache

---

wa/workloads/recentfling/__init__.py

workloads: add recentfling

---

wa/framework/configuration/core.py
wa/framework/configuration/parsers.py
wa/framework/configuration/tree.py

Add logging to config/agenda parsing.

fw/config: add logging to parsers

---

wa/workloads/meabo/__init__.py

Add automation for meabo micro-benchmark.

workloads: add meabo

---

wa/workloads/rt_app/__init__.py

The rt-app workload parses the rt-app JSON file in order to override
some options (specifically duration). Previously, if the JSON was
syntactically incorrect, an uninformative ValueError was raised. Now
we raise a ConfigError with appropriate message prompting the user to
fix the file.

workload/rt-app: Better JSON processing error reporting

---

wa/framework/entrypoint.py
wa/framework/execution.py
wa/framework/output.py
wa/framework/plugin.py
wa/framework/version.py

- Add missing __str__ implementations to some classes to improve
readability of logs/interactive shell output.
- Add the commit hash (if available) to the version recorded in run.log.

Minor enhancements

---

wa/commands/process.py
wa/framework/execution.py
wa/framework/job.py
wa/framework/output_processor.py
wa/instruments/trace_cmd.py
wa/output_processors/cpustates.py
wa/utils/cpustates.py
wa/utils/trace_cmd.py

- Port cpustates processor from WA2, fixing the big.LITTLE idle state mismatch
issue.
- process command improvements
- job logging improvements
- trace-cmd parser refactor

Port cpustates processor + bits

---

wa/commands/show.py
wa/utils/doc.py
wa/workloads/openssl/__init__.py

- Document aliases as part of a plugin's documentation.
- Handle aliases as arguments to the show command.
- Add openssl workload.

openssl workload + further alias fixes.

---

doc/source/developer_reference/writing_plugins.rst
doc/source/how_tos/developers/adding_plugins.rst
wa/commands/templates/apk_workload
wa/commands/templates/apkrevent_workload
wa/commands/templates/apkuiauto_workload
wa/commands/templates/basic_workload
wa/commands/templates/revent_workload
wa/commands/templates/uiauto_workload
wa/framework/execution.py
wa/framework/output.py
wa/framework/workload.py
wa/instruments/poller/__init__.py
wa/utils/serializer.py
wa/workloads/dhrystone/__init__.py
wa/workloads/hackbench/__init__.py
wa/workloads/hwuitest/__init__.py
wa/workloads/meabo/__init__.py
wa/workloads/memcpy/__init__.py
wa/workloads/openssl/__init__.py
wa/workloads/recentfling/__init__.py
wa/workloads/rt_app/__init__.py
wa/workloads/stress_ng/__init__.py
wa/workloads/sysbench/__init__.py

Use this new capability to track android app version and resource hash
tracking.

Implement metadata recording inside results.

---

doc/source/changes.rst

- Reword the intro and add a solicitation for porting requests.
- Move "new features" to above "changes".
- List a bunch of additional new features.

doc: jazz up "What's new" section

---

doc/build_instrument_method_map.py
wa/__init__.py
wa/framework/instrument.py
wa/framework/signal.py

- Update table header in generated docs
- Use enum for signal priorities
- Use signal priorities for instrument decorators

Fixes to instrument priorities.

---

wa/framework/target/descriptor.py

Added support for specifying target parameters in the Platform tuple.

Add target-params to Platform Tuple

---

wa/workloads/deepbench/__init__.py

Add automation for Baidu's DeepBench benchmark for deep learning
operations.

workloads: add deepbench

---

setup.py
wa/__init__.py
wa/framework/entrypoint.py

- implement PEP396
- log devlib version during run
- add commit to install version
Note: this depends on https://github.com/ARM-software/devlib/pull/286

PEP396 + bits

---

setup.py
wa/commands/process.py

Write job_output result to make sure the serialized version gets
updated.

command/process: write job_output result

---

wa/commands/revent.py
wa/workloads/apache.py

Add a benchmark that load-tests Apache server installed on the target.

workloads: add apache benchmark

---

wa/output_processors/sqlite.py

Correct the word connecton to connection.

output_processor/sqlite: Fix typo in function name

---

dev_scripts/README
dev_scripts/copyright_updater

Add copyright_updater script which checks Python files to ensure their
copyright is up to date with its last modification.

dev_scripts: add copyright_updater

---

extras/Dockerfile

Update to use the latest release version of WA and devlib.

extras/Dockerfile: Update to use latest releases

---

setup.py

- Add URL for the package pointing to the GitHub repo
- Add -s option to sdist command that strips away the git commit
hash from the generated package version (needed for upload to
PyPI).

setup.py: prepare for the 3.0.0 release

---

doc/source/user_information/user_guide.rst
setup.py

- Update 'setup.py' package name to 'wlauto' as 'wa' is already taken on
PyPi and update documentation accordingly.
- Update old references to Python 2.7

wa: 3.0.0 Release preparation

---

doc/source/user_information/user_reference/configuration.rst
tests/data/includes/agenda.yaml
tests/data/includes/configs/test.yaml
tests/data/includes/section-include.yaml
tests/data/includes/sections/section1.yaml
tests/data/includes/sections/section2.yaml
tests/data/includes/user/config.yaml
tests/data/includes/workloads.yaml
tests/test_agenda_parser.py
wa/commands/run.py
wa/framework/configuration/execution.py
wa/framework/configuration/parsers.py

This implements feature request: https://github.com/ARM-software/workload-automation/issues/648

Add the ability to include files inside config/agendas

---

wa/instruments/perf.py

Dependant on https://github.com/ARM-software/devlib/pull/307

instruments/perf: Port the perf instrument to WA3

---

setup.py
wa/commands/create.py
wa/commands/postgres_schema.sql
wa/commands/schema_changelog.rst
wa/output_processors/postgresql.py
wa/utils/postgres_convert.py

Add the WA Command to create a Postgres database, the schema for the database which stores the results found in the wa_output folder, and last but not least the Postgres Output Processor used to upload to the database.

Postgres Output Processor and WA Create Database Command

---

doc/source/user_information/how_tos/device_setup.rst
setup.py
wa/commands/create.py
wa/framework/target/descriptor.py
wa/framework/target/manager.py
wa/framework/version.py
wa/instruments/misc.py
wa/output_processors/cpustates.py
wa/output_processors/csvproc.py
wa/output_processors/postgresql.py
wa/output_processors/sqlite.py

Dependant on https://github.com/ARM-software/devlib/pull/320

Misc Fixes

---

wa/output_processors/postgresql.py

Refactor and fix uploading duplication.

Postgres Output Processor Updated

---

doc/source/changes.rst
extras/Dockerfile
setup.py
wa/framework/entrypoint.py
wa/framework/target/info.py
wa/framework/version.py

Dependant on https://github.com/ARM-software/devlib/pull/372

[RFC] Devlib Version Improvements + Version Bump

---

extras/Dockerfile

Update the base ubunutu image to 18.10 and switch to using Python3 for
installing WA.

Dockerfile: Update to newer base and Python version

---

wa/commands/templates/setup.template
wa/commands/templates/uiauto/uiauto_build_script
wa/workloads/adobereader/uiauto/build.sh
wa/workloads/aitutu/uiauto/build.sh
wa/workloads/androbench/uiauto/build.sh
wa/workloads/antutu/uiauto/build.sh
wa/workloads/applaunch/uiauto/build.sh
wa/workloads/benchmarkpi/uiauto/build.sh
wa/workloads/chrome/uiauto/build.sh
wa/workloads/geekbench/uiauto/build.sh
wa/workloads/gfxbench/uiauto/build.sh
wa/workloads/glbenchmark/uiauto/build.sh
wa/workloads/gmail/uiauto/build.sh
wa/workloads/googlemaps/uiauto/build.sh
wa/workloads/googlephotos/uiauto/build.sh
wa/workloads/googleplaybooks/uiauto/build.sh
wa/workloads/googleslides/uiauto/build.sh
wa/workloads/motionmark/uiauto/build.sh
wa/workloads/pcmark/uiauto/build.sh
wa/workloads/rt_app/__init__.py
wa/workloads/rt_app/workgen
wa/workloads/speedometer/uiauto/build.sh
wa/workloads/vellamo/uiauto/build.sh
wa/workloads/youtube/uiauto/build.sh

Update Uiautomator build scripts and package setup template to be python 3 compatible.

Python3 Updates

---

wa/output_processors/cpustates.py
wa/utils/cpustates.py

Improvements to the cpustate output processor when dealing with missing information.

Cpustates Improvments

---

wa/instruments/perf.py
wa/instruments/screencap.py
wa/instruments/serialmon.py
wa/instruments/trace_cmd.py
wa/utils/trace_cmd.py

Update the WA instruments which rely on the refactored devlib collectors
to reflect the new API.
Dependant on https://github.com/ARM-software/devlib/pull/454

wa/instruments: Refactor collectors to use Collector Inferface

---

wa/framework/getters.py
wa/utils/types.py

Update to support Apks using strings in their `versionName`.

Apk version fix

---

wa/commands/process.py

- Correct handling of skipped jobs -- the output directory would not
have been generated, so do not try to write it.
- Do not attempt to process runs that are in progress, unless forced,
and do not try to process jobs that have not completed yet.
- Write the run info as well as the result, allowing output processors
to modify it (e.g. adjusting run names).

commands/process: partial results + write info

---

wa/instruments/proc_stat/__init__.py
wa/instruments/proc_stat/gather-load.sh

Add an instrument that monitors CPU load using data from /proc/stat

instruments: add proc_stat

---

wa/framework/configuration/core.py
wa/framework/plugin.py
wa/framework/target/descriptor.py
wa/framework/version.py

Update WA to accommodate the new SSH connection implementation in devlib.
Dependant on: https://github.com/ARM-software/devlib/pull/450

[WIP] Update For Paramiko based SSH and depreciated parameters

---

wa/framework/target/descriptor.py

- Allow for specifying a list of `Platforms` that a particular target does
not support, e.g. 'local_juno'
- Rework how parameter defaults are overridden to allow overriding the entire parameter object rather than only the default value for a particular platform.
- Allow for overriding connection parameters on a per platform basis.
- Make the `host` parameter for `Juno` optional.
Fixes #961

Target descriptor fixes

---

wa/framework/target/descriptor.py
wa/framework/version.py
wa/instruments/serialmon.py
wa/utils/types.py

Dependent on https://github.com/ARM-software/devlib/pull/485

Paramiko Improvmentes 

---

wa/framework/version.py

Bump the development version to synchronise the parameters for transfer
polling.

fw/version: Development version bump

---

wa/framework/execution.py
wa/workloads/speedometer/__init__.py

Add Package Check to Speedometer 

---

wa/utils/doc.py

The "name" can be in the format "<class>.<lambda>" so
update to allow correct function with the updated format.

utils/doc: Fix output for lambda function

---

requirements.txt

See https://github.com/pypa/pip/issues/4022

Remove pkg-resources at borked version

---

doc/source/developer_information/developer_reference/contributing.rst

Update the Contributing/Code section with instruction to rebuild the UI
automation APK if the corresponding source has been update.

doc: update coding guide with APK rebuild info

---

doc/source/developer_information/how_tos/adding_plugins.rst

Fix the example instrument code and add additional note to indicate where new plugins should be stored to be detected by WA's default configuration to improve clarity.
Fixes issues raised in https://github.com/ARM-software/workload-automation/issues/1201

docs: Update plugin How To Guides

---

wa/instruments/perfetto.py
wa/instruments/trace_cmd.py

This PR intends to add a Perfetto instrument that allows workload-automation to attach collecting a Perfetto trace to a running workload.

instruments: Add Perfetto instrument

---

wa/framework/configuration/parsers.py

The key for 'include#' can now be either a scalar or a list. A scalar triggers the same behaviour as before.
If the value is a list it must be a list of scalars (filepaths). The paths will be loaded and merged in order, and finally the resulting dict is included into the current scope.

configuration: Allow including multiple files into one mapping.

---

wa/framework/version.py

Bump the require devlib version that exports new trace-command functionality.

version: Bump required devlib version
