ARM-software/workload-automation

wlauto/core/extension.py
The param documentation states that for a boolean, "kind" should be
"as_bool" from wlauto.utils.misc, but there is no "as_bool".  Currently,
workload automation automatically converts native python types like bool
and int to workload automation specific ones.  Remove this bit from the
documentation as it's not true any more.
=> Fix Param documentation

wlauto/result_processors/ipynb_exporter/__init__.py, wlauto/result_processors/ipynb_exporter/template.ipynb
Changelog since v1:
- Fix ipython and jinja2 imports
- Use context.run_output_directory instead of
settings.output_directory
- Remove "The following settings may be specified in config.py or in
the agenda:" from the description
- Format documentation as reStructured Text
- Pass the RunResult and ExecutionContext objects to the template
instead of a list of paths
- Add a simpler example that uses matplotlib and make it part of the
documentation
- Strip "_at_end" from the "show_notebook" and "show_pdf" parameters
- Clarified the description of the notebook_directory parameter
- Set "convert_to_pdf" if "show_pdf" is set instead of failing
- Use wlauto.utils.misc.open_file() to open the PDF
=> Add an ipython notebook exporter results_processor

wlauto/result_processors/ipynb_exporter/__init__.py
I ran first pep8 and then pylint, so I missed the pep8 errors introduced
by me shutting up pylint 😇
=> Fix pep8 errors in ipynb_exporter

wlauto/result_processors/notify.py
This result processor displays a desktop notification when the run
finishes.  It's useful when you are running a long agenda in WA and want
to be notified when the results are available.
=> Add a notify result processor

wlauto/result_processors/ipynb_exporter/__init__.py, wlauto/utils/ipython.py
Apart from easing ipython 3 support, this pull request removes the splat that you got when running WA with ipython 3 installed:
UserWarning: IPython.nbformat.current is deprecated.
- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version
Additionally, if you try to use the results processor with ipython version 3, it will tell you that the version is currently not supported.  Support for that version is still work in progress.
=> Generic Ipynb_exporter improvements to ease ipython 3 support

wlauto/core/configuration.py
Commit 2276ae0c5b54 ("Fixing config processing for extensions with
non-identifier names.") broke customizing the trace-cmd instrumentation
from the agenda.  With an agenda like:
config:
instrumentation: [trace-cmd, delay]
trace_events: ['thermal*']
trace_buffer_size: 28000
trace_events and trace_buffer_size get added to the RunConfiguration's
_raw_config under the trace-cmd name, but then when it's looked up in
_finalize_config_list(), the dictionary is actually looked up using
identifier(extname), i.e. 'trace_cmd'.  Fix this by adding the user's
configuration using identifier(name) as well.
=> Fix trace-cmd after 2276ae0c5b54

wlauto/config_example.py, wlauto/instrumentation/daq/__init__.py, wlauto/instrumentation/hwmon/__init__.py, wlauto/instrumentation/perf/__init__.py, wlauto/instrumentation/pmu_logger/__init__.py
Some options in config_example.py are not reachable. It makes users
confused. So make the options in the file as gobal_alias.
Signed-off-by: zhizhou.zhang <zhizhou.zhang@spreadtrum.com>
=> get options in config_example.py reachable

wlauto/instrumentation/perf/__init__.py
Remove the CCIPerfEvent class since it's no longer used in WA.
=> perf: remove CCIPerfEvent class

wlauto/result_processors/ipynb_exporter/__init__.py, wlauto/utils/ipython.py
Add a couple of options to the `ipynb_exporter` so that it can create static html versions of the notebook.
=> ipynb_exporter convert to html

wlauto/devices/android/juno/__init__.py
There's a known issue that HDMI will lose sync with monitor, adding video kernel parameter will make the HDMI more stable for juno
> HDMI can lose sync with the monitor intermittently, particularly at higher resolutions. 
> If you are affected by this then try adding a kernel command line argument that forces 
> a video mode with reduced blanking, such as the following:
> video=DVI-D-1:1920x1080R@60
=> passing 'video' command line to Juno kernel

wlauto/instrumentation/trace_cmd/__init__.py
The warning refers to trace.bin, which is not the extension that we use
for it.  Instead, use the variable with the default trace
name (trace.dat) for the warning.
=> trace: fix data file trace name in warning

wlauto/instrumentation/freqsweep/__init__.py
E.g:
sweeps:
- cluster: a15
runtime_params:
a15_cores: 1
=> Freqsweep: Added the ability to specify workload/runtime parameters

wlauto/common/gem5/device.py, wlauto/devices/android/gem5/__init__.py, wlauto/devices/linux/gem5/__init__.py
- This patch addresses an issue with the arguments passed the
BaseGem5Device __init__. With this patch these are no longer passed
in as they are not required in the base device implementation.
=> Gem5Device: Fix issue with init arguments

wlauto/devices/android/juno/__init__.py
Juno's bootargs parameter specifies the kernel boot arguments as a
sigle string. However, when it is passed into _boot_via_uboot, it was
expanded as a mapping, causing an error. This fixes that boneheaded
mistake...
=> juno: fixing a stupid error in u-boot boot path

wlauto/workloads/applaunch/__init__.py
Since cleanup test block is defined in the device_script.template, the
value of cleanup is needed to render the template properly.
Signed-off-by: Chase Qi <chase.qi@linaro.org>
=> applaunch: pass cleanup argument to the template

wlauto/common/android/device.py
As of android M ps can no longer filter by process name. This is
now handled using grep from busybox.
As part of this busybox is now deployed to non-rooted as well as
rooted devices.
=> AndroidDevice: fixed get_pids_of

wlauto/workloads/applaunch/__init__.py, wlauto/workloads/applaunch/device_script.template
When IO is heavily loaded, the impact of IO schedulers on App launch
time varies. To measure the impact, added io_stress and io_scheduler two
parameters and related jinja2 blocks.
Signed-off-by: Chase Qi <chase.qi@linaro.org>
=> applaunch: Added support for IO scheduler test

wlauto/core/extension.py, wlauto/tests/test_extension.py
Previously you could have `override` set to True on parameters that
only existed in the current scope.
Now if you try to override a parameter that doesn't exist higher up
in the hiarchy you will get a ValueError.
=> Parameter: Fixed overriding of new parameters

wlauto/utils/ipython.py
This is a fix for
https://github.com/ARM-software/workload-automation/issues/97
IPython can use rc tags in its version strings, which StrictVersion
can't handle.
=> ipython: switched to using LooseVersion for version checks.

wlauto/common/android/workload.py, wlauto/utils/android.py
"Normal" android permissions are automatically granted and cannot
be changed. Trying to "pm grant" these caused an error, this should
no longer occur.
=> ApkWorkload: Fixed runtime permission granting

wlauto/core/entry_point.py
This is just to provide a friendlier error message.
Before this commit you get an IOError from imp.load_source.
This only changes the behaviour when using "--config".
=> Add entry_point check for config file existence

wlauto/common/linux/device.py, wlauto/utils/ssh.py
- Deal with the dropped connection on issuing "reboot"
- Introduced a fixed initial delay before polling for connection to
avoid re-connecting to adevice that is still in the process of
shutting down.
=> LinuxDevice: fixed reboot.

wlauto/commands/run.py
If the specified agenda argument is not found in the file system, WA
assumes it is the name of a workload and would then raise an "extension
not found error", which may be confusing if the user's intension was to
specify a path.
Now, WA will first check that neither path separator, nor a '.' are
present in the agenda argument before assuming it is a workload name, and
will provide a less confusing error in that case.
=> run command: more usefull error message when specifying non-existing agenda path

wlauto/instrumentation/daq/__init__.py
The daq instrument will no longer accept duplicate channel names.
This caused issues where files sent from the daq sever were being
overwritten.
=> daq: Added check for duplicate channel labels

wlauto/instrumentation/daq/__init__.py
Fixed channel merging when setting merge to True.
Channel merges done by setting a mapping manually were not affected by this bug.
=> daq: Fixed channel merging

wlauto/workloads/applaunch/__init__.py, wlauto/workloads/applaunch/device_script.template
applaunch creates and deploys an auxilary script in order to collect
precise timings. This script invoked busybox with the assumption that it
is in PATH.
Since recent changes mean that it is no longer deployed to /system/bin,
the busybox in not found. With this commit, the full path to busybox
will be passed into the script's template.
=> applaunch: pass the location of busybox into the script

wlauto/workloads/sysbench/__init__.py
Use the full path to busybox on the target device as opposed to
assuming it is found on the path.
=> sysbench: use device busybox binary

wlauto/common/linux/device.py
Before they were cat'ed this gave garbage output for compressed files.
Cat-ing is necessary since not all properties are normal files (sysfs).
=> BaseLinuxDevice: gzipped property files are now zcat'ed

wlauto/core/resolver.py
If the ResourceResolver was looking for a specific version of a
resource and could not find it, this version number is now shown
in the error message.
=> ResourceResolver: Show version number when resource wasn't found.

wlauto/common/android/workload.py
If the package has no defined launch activity you must call the
activity manager in a different way.
=> Fix for packages without launch activities

wlauto/workloads/glbcorp/__init__.py
- Fixed launching of the benchmark due to: ff5f48b7e70117dc4161f2bd986438450f73cc16
- Updated regex to match new logcat format
=> glbench updates

wlauto/commands/run.py
Previously if no worklaod specs were loaded, WA would still start instruments
and then go immediately to the teardown stage. This no longer happens.
=> Executor: WA no longer runs with no workloads specs

wlauto/commands/templates/android_benchmark, wlauto/commands/templates/android_uiauto_benchmark, wlauto/commands/templates/basic_workload, wlauto/commands/templates/uiauto_workload
Parameter name in workload templates updated to be a valid identifier.
=> create command: fix example parameter name in templates

wlauto/devices/android/juno/__init__.py, wlauto/utils/uboot.py
juno:
- The default boot args have been removed since these cause issues with the latest Linaro builds, which boot correctly without any bootargs.
- made a regex string a raw-string.
uboot: 
- Now detects the U-Boot version to use correct line endings
=> Juno fixes

wlauto/instrumentation/misc/__init__.py
Commit 724f6e590e8ba3c2251e864e4216cf258ae7a861 changed sysfile_getter
behavior to first tar up copied files and then gzip them. Tarball name
needs to be updated to not include '.gz' extension.
=> sysfile_getter/cpufreq: fix taball name

wlauto/result_processors/cpustate.py, wlauto/utils/power.py
Previously, only reports that were generated were returned. With this
commit, there will be an entry for each active reporter in the returned
list. If a reporter did not produce a valid report, the entry will be
None.
This ensures consistent output, even if a run time issue causes a
reporter not to produce a report  (e.g. if cpufreq events were not
enabled).
=> report_power_stats: number of entries returned always matches number of reporters

wlauto/common/linux/device.py
- Updated `kick_off` to behave like the Android version
- Updated `killall` to behave like `kick_off` since if something is run as root, root has to kill it/
- Removed unused function `has_root`
=> LinuxDevice fixes

wlauto/common/android/workload.py, wlauto/resource_getters/standard.py
- Device model name is now used when searching for revent files
- All revent instances are killed during teardown (kills revent if run aborted)
=> Revent fixes

wlauto/instrumentation/misc/__init__.py
If the tar.gz already existed on the target device the instruments would
fail. This fix adds the "-f" option to gzip to force it to overwrite the
file.
=> sysfs_extractor & cpufreq: Fixed error when tar.gz file already existed

wlauto/utils/android.py, wlauto/utils/misc.py, wlauto/utils/ssh.py
Standard string representation of a subprocess.CalledProcessError does
not include the output of the command, so it was not previsouly included
in the resulting DeviceError. This commit ensures that the output is
propagated, regardless of whether it came from stdout or stderr of the
underlying process.
=> LinuxDevice: error output for pull/push_file

wlauto/workloads/bbench/__init__.py
Added a change in bbench workload. This will enable to grant permission to any browser. Currently, it was not working for chrome browser.
=> Permission granted for generic browser

wlauto/workloads/geekbench/__init__.py
After running the benchmark, when collecting the output files the execution
fails because the split('\n') call, used for creating a list of output files,
returns an empty string as last element. The empty string makes the pull command
fail because file '' doesn't exist on the target device.
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>
=> geekbench: fix output files listing

wlauto/common/android/device.py, wlauto/common/android/resources.py, wlauto/common/android/workload.py, wlauto/resource_getters/standard.py, wlauto/workloads/dex2oat/__init__.py, wlauto/workloads/peacekeeper/__init__.py
Opening this for discussion, originally was [this PR](https://github.com/jimboatarm/workload-automation/pull/118)
**Replace APK during install**
- Use `-g` and `-r` flags with `adb install` if necessary. The `-g` flag is used to grant all runtime permissions at installation time on API 23 and above. The `-r` flag tells `adb` to replace existing APK if found (sometimes uninstall does not fully remove the package e.g. for built-in apps).
**Check APK version and ABI**
- When the `version` attribute is specified in the workload, the execution will now validate it against the provided APK's `versionName` property, and raise a `WorkloadError` if they do not match.
- Added `check_apk_abi` parameter to `ApkWorkload` which is disabled by default. If enabled in the workload/agenda, the resource …
=> Apk version check

wlauto/resource_getters/standard.py
Because UNIX tells us that "everything is a file".
=> resource getters: weaken File to also resove to directories

wlauto/common/linux/device.py
Add a general check that pings a network host rather than checking the
status of dumpsys wifi due to the fact that not all devices are
connected via wifi. Intended for workloads that require an internet
connection to operate.
=> Add network connectivity check for devices

wlauto/common/android/device.py, wlauto/core/execution.py
Dump window hierarchy view from uiautomator to a file when WA fails
during execution. Note: the xml file are pre-formatted after dump.
Implementation specific to android.device.
=> Dump hierarchy view on error

doc/source/revent.rst, setup.py, wlauto/common/android/workload.py, wlauto/utils/statedetect.py
- Added statedetect.py in utils which is a standalone module that
contains all the methods needed for state detection
- Modified the setup() and run() methods of the GameWorkload class
in common/android/workload.py to have a parameter that enables
state checks and run the check after setup and run if requested.
State detection uses the template matching method available in
OpenCV to determine the state of the workload by detecting
predefined unique elements on a screenshot from the device.
=> Implemented visual state detection functionality for revent workloads

wlauto/utils/misc.py, wlauto/utils/ssh.py
CalledProcessErrorWithStderr is a subclass of CalledProcessError that
also takes stderr output. Both that and normal output must be passed as
keyword arguments. They were being passed as keyword arguments inside
_scp() of SshConnection, causing cryptic errors to appear.
=> ssh: fixing rasing of CalledProcessErrorWithStderr

wlauto/common/android/device.py
New method to force a re-index of the mediaserver cache for the
specified directory. Used in workloads that require external media files
as dependencies.
=> Add broadcast_media_mounted method to android device

wlauto/common/android/workload.py, wlauto/common/linux/device.py, wlauto/core/device.py, wlauto/core/workload.py
- Device subclasses should provide their own implementation.
Default behaviour is to raise a `NotImplementedError`
- Workload subclasses can set `requires_network` to `True` and
network connectivity check will be performed during `setup()`
=> Add network check methods to Device and Workload classes

wlauto/common/android/workload.py
Implement new method to enforce that a valid apk version is used to run
the workload. Based on a min and max range of apk versions tested
during development.
=> Add check_app_version method to AndroidUxPerfWorkload

wlauto/common/android/workload.py
Super works by having a iterator of parent classes to ensure each is called
once and only once. WA calls some parent methods in classes with multiple
inheritenceconditionally so calls them directly instread. This breaks super
which ends up calling some methods multiple times.
To work around this until workloads are reworked to use composition rather than
inheritance, all classes that that subclass `Workload` directly no longer use
`super`.
=> Workloads: Fixed issues with calling super

wlauto/workloads/antutu/__init__.py, wlauto/workloads/geekbench/__init__.py, wlauto/workloads/glbenchmark/__init__.py
In a recent commit workload versions were changed to match their APK versions.
This commit adds the old versions to the allowed versions and automatically
maps them onto the new values.
=> workloads: Fixed versions to be backward compatible

wlauto/common/android/workload.py
Since initilize only runs once per workload, we can't set variables required
for each iteration in initilize. Revent workload was setting its file paths
in initilize, now moved to setup.
=> ReventWorkload:Fixed revent workloads with multiple iterations

wlauto/common/android/workload.py
Previously if trying to downgrade an app using the `-r` option of
`adb install` the `INSTALL_FAILED_VERSION_DOWNGRADE` error would occur.
The app is now uninstalled first to prevent this.
=> ApkWorkload: Fixed replacing apps on a device

.gitignore
Gitignore was untracking a few files from wlauto/external/uiautomator whereas
the folder name is uiauto instead. Name changing done to fix the bug.
=> Fixes gitignore to untrack files from uiauto

wlauto/resource_getters/standard.py
Executables were not previously automatically downloaded from a
provided remote_assets_url. The http_getter is now called to attempt to
find and download executable files.
=> ResourceGetters: Updated executable discovery to use http_getter

doc/source/revent.rst, wlauto/commands/record.py, wlauto/external/revent/revent.c
Changed termination signal to interrupt signal to prevent code exiting too early.
Added exit handler to ensure revent exits correctly as previously was
crashing and therefore not running final code.
Fixed error in writing input event where half of timestamp seconds was missing.
Fixed typo in documentation for revent file structure.
=> Revent: Fixes

wlauto/workloads/dex2oat/__init__.py
Command fails to execute with permission error on some devices therefore
now attempts to use root if available.
=> Dex2oat: Now uses root if available.

wlauto/instrumentation/netstats/__init__.py
Android marshmallow uses a different default view for logcat
therefore prevented output from being extracted. The regex
expression has been updated to include matching the new format.
=> NetStat: Updated Regex to match logcat format in android 6.0

wlauto/agenda-example-biglittle.yaml
One of the workloads was listed as sqlite which is an instrument,
corrected the workload name to sqlitebm.
Added missing word in description.
=> big.Little Sample Agenda: Fixed workload name and typo.

wlauto/workloads/skype/__init__.py
Skype has a unique launch command which is called in the setup
phase of the workload. The launch command is split into a stand alone
method which can be called as a separate method if required.
This can be used as common method if more applications in future
require their own customized launch command.
=> Create a function for launching skype application.

wlauto/common/android/workload.py
Apkworkload setup phase performs many functionalities in
a single method that is broken down into short methods.
The split short methods can be called individually when
relevant use cases arise.
=> Splits ApkWorkload setup() into short methods.

wlauto/workloads/applaunch/__init__.py
Application launch workload runs the package of the workload which is being
instrumented. Fps instrumentation requires the package name and hence the
package name is changed to the workload package name during initialization.
Tested on Huawei Mate8 with fps instrumentation ON.
=> Applaunch: Update package to measured workload pkg.

wlauto/instrumentation/fps/__init__.py
to fallback to SurfaceFlinger method when run on Android M and above
=> Allow user to override the method of collecting FPS data,

wlauto/workloads/audio/__init__.py
In this changeset we remove some left over browser specific commands
which are no longer required as part of the audio workload.
=> Remove stale browser-specific commands from audio workload

wlauto/core/device.py, wlauto/workloads/apklaunch/__init__.py, wlauto/workloads/applaunch/__init__.py, wlauto/workloads/audio/__init__.py, wlauto/workloads/bbench/__init__.py, wlauto/workloads/citadel/__init__.py, wlauto/workloads/cyclictest/__init__.py, wlauto/workloads/facebook/__init__.py, wlauto/workloads/glbcorp/__init__.py, wlauto/workloads/homescreen/__init__.py, wlauto/workloads/idle/__init__.py, wlauto/workloads/manual/__init__.py, wlauto/workloads/nenamark/__init__.py, wlauto/workloads/thechase/__init__.py, wlauto/workloads/video/__init__.py
This changeset adds the ability to sleep on the device via a
device.sleep() method. This invokes sleep on the target device. This
is useful for situations where the passage of time on the target
device does not match that of the host, e.g., gem5.
This changeset also updates a number of workloads to use this new
sleep method.
=> Extend device with sleep functionality

wlauto/common/linux/device.py, wlauto/core/device.py
`set_sysfile_values` now accepts a `^` symbol prefixed to the
file path to indicated that the value should be written as binary data.
To accommodate this an extra `binary` flag has been added to  the `set_sysfile_value`and `get_sysfile_value` methods to write and retrieve the binary data respectively.
=> Device: Updated to set and retrieve binary data from sysfiles

wa/workloads/idle.py
In the case where the device screen was off prior to the execution of
the workload, but the user did not set screen_off, the screen will be
turned on during the setup. Previously, it would remain on for the
subsequent execution, however the correct behavior is for the workload
to always restore the screen to its previous state.
=> idle: makes sure screen is off if was off before

wa/workloads/idle.py
In the teardown, if screen_off was not set, only ensure that the
screen is on for Android targets.
=> idle: do not attempt to turn off screen on Linux

wa/utils/trace-cmd.py
This re-adds the parser for the trace-cmd text trace, after it got
dropped along with wlauto sub-tree. There are minor differences from the
old WA2 parser.
- Changed to work with devlib start/stop markers
- TraceCmdTrace renamed to TraceCmdParser
- The file path is now passed to the parse() method rather than
on creation.
- detect whether markers are present in the trace and do not filter
if they aren't
=> trace-cmd: Add parser for text trace.

wlauto/utils/trace_cmd.py
Added parsers for sched_wakeup(_new) and sched_stat_* events that have
non-standard text.
=> utils/trace_cmd: add parsers for more sched events

wlauto/core/entry_point.py
When [Jenkins abort a job it sends a TERM signal](https://gist.github.com/datagrok/dfe9604cb907523f4a2f), at the moment WA only handles INT (i.e KeyboardInterrupt), this patch is to trap TERM signals and raise a KeyboardInterrupt instead.
=> Convert TERM signals into INT to allow WA to exit cleanly

wlauto/core/entry_point.py
Due to a local file named 'signal.py' this was being imported instead of the system level 'signal' package. This commit ensures the the system level is used instead.
=> EntryPoint: Fixes local package being used over system level

wlauto/common/linux/device.py, wlauto/core/execution.py
I believe `active_cpus` was removed and replaced by `online_cpus` but linux/device.py still seems to reference `active_cpus`
I'm creating the pull request with the fix now, so that our test infrastructure can pick it up and test it.
I'll confirm in a later message whether or not it fixes the issue.
=> Replaced active_cpus by online_cpus in common/linux/device.py

wlauto/common/android/workload.py
After the upgrade to uiauto2 some workloads seem to take slightly longer
than previously.
=> Workload: Increased default uiautomator workload timeout

wlauto/instrumentation/fps/__init__.py
Some versions of Android include additional fields in gfinxo which we
don't care about. The existing fields have the same order, so simply
ignore the extra ones.
=> fps: Ignore additional fields in gfxinfo frame data

wlauto/common/android/workload.py
Due to the fact that uiauto apk files built on different machines will
be signed with different keys, adb will fail to overwrite a previous
version even when set to replace. This commit now will uninstall the
previous uiauto apk file if present before attempting to install the new
version.
=> AndroidWorkload: Uninstall uiauto apks before reinstalling

wlauto/utils/power.py
If a frequency transition is observed before an idle state can be
established, assume idle state is -1 (i.e. the core is running). This
will ensure correct stats for platforms with disabled cpuidle.
=> cpustates: fix idle state assumption on freq transition

wlauto/instrumentation/acmecape/__init__.py
Add an instrument for collecting power and energy from BayLibre
ACME cape probe.
This is an alternative implementation to:
https://github.com/ARM-software/workload-automation/pull/407 and should be
reviewed in concert.
=> instrumetnation: add support for BayLibre ACME cape

wlauto/utils/power.py
This reverts commit 9bd745b347ef1a18a8b46a07cf5fa6dd3af642f8.
When a frequency is changed on a core, cpufreq reports a frequency
transition for all cores in the frequency domain. This means it is not
safe to assume a core is not idling just because there is a frequency
transition reported for it (that just means that there is at least one
core on that frequency domain that is not idling). Moreover, the
transitions are always reported in the same order so there is no way to
infer which core triggered it.
=> Revert "cpustates: fix idle state assumption on freq transition"

wlauto/result_processors/cpustate.py, wlauto/utils/power.py
Add "no_idle" parameter to work around the problem where cores are
reported to be in "unknown" state if there are no cpuidle transitions in
the trace. If this parameter is set set, cpustates will assume cores are
active without waiting for an idle transition.
=> cpustates: workaround for disabled cpuidle

wlauto/common/android/workload.py
Attempting to uninstall an non-existing package will result in an error.
So, when replace=True for install_apk(), only attempt to uninstall if
the package is already present on the target.
=> ApkWorkload: only uninstall if package is already installed

tests/test_utils.py, wa/utils/types.py
Add to/from_pod implementations to level, so that it may be serialized
properly. In order to make sure that serialization is a reversible
operation, ensure that the level value is numeric.
=> types: make enum levels serializable

wa/framework/configuration/parsers.py
When both global and config sections are present in an agenda, they both
will be processed by the ConfigManager. In each case, the path to the
agenda file was specified as the source, which resulted ConfigManager
complaining that the same source is being added twice. To avoid that,
the source is now suffixed with the section name.
=> AgendaPaser: fix duplicate source error

wlauto/common/android/device.py
Ran into a development target on which one of the values in getprop
output contained a new line. Updating getprop parsing logic to handle
such cases by switching to a regex.
=> AndroidDevice: more robust getprop parsing

wlauto/instrumentation/trace_cmd/__init__.py
The interactive governor isn't standard any more (and was
Android-only anyway). Remove this default so you don't get errors for
kernels that don't support it.
=> trace-cmd: remove cpufreq_interactive from default events

wlauto/instrumentation/trace_cmd/__init__.py
Following from this discussion:
https://github.com/ARM-software/workload-automation/commit/4d7ef408c97099658a340af4c9ed04154833ee69
- Remove reference to default events from the overall workload
documentation. It was, as of recently, outdated, and was also
redundant, as the actual defaults will be in the parameter-specific
documentation.
- Remove reference to Android-specific trace-cmd binary -- this was not
true for a long time.
- Clarify that the on-host trace-cmd binary is now optional due to the
report_on_target config.
- Fix a few misc typos.
=> trace-cmd: documentation fixes.

wlauto/utils/android.py
Provide the stdout/stderr text as part of the messsage in the
exception raised when no exit code can be identified from the adb
command output.
=> utils/android: better error massage when no exit code found

wlauto/common/android/device.py
install_apk() was using the default timeout of 30 seconds, this can
cause problems for some applications on slower targets. Since
installation is expected to be a long-ish operation, there is not reason
for the timeout to be this short.
This commit adjusts the timetout to 5 minutes, which should be a more
reasonable value for most applications. For some apps with particularly
large APKs, this may not be enough, but in those cases, the default
should already be overriden on per-worload bases.
=> AndroidDevice: adjust APK install timeout to 5min

wlauto/utils/trace_cmd.py
The combined effect of these optimizations is it reduced the time take to loop
over all events in a trace containing 1.5M events from ~70s to ~11s.
- Not using regex to parse events saves ~39s
- Not parsing event bodies unnecessarily saves ~18s*
- Not matching every line against preamble/dropped events regex's saves ~2s
*The benchmark just looped over events; it did not try to access any fields,
so no bodies were parsed. A typical script would usually access fields in
some of the events, so this optimization would not be as impactful, but it
should still effect a significant saving by not parsing all of event bodies.
=> Optimize parsing of trace-cmd output

wlauto/utils/trace_cmd.py
Make event preamble parsing more robust in cases there are multiple
instances of ' [' (e.g. as part of thread name) by splitting exactly
once from the right. The right-most columns are the timestamp and the
cpu id, and much more restricted (and therefore predictable) in their
formatting.
=> utils/trace_cmd: fix event parsing

wa/framework/target/runtime_config.py, wa/utils/misc.py
get_domain_cpus() got renamed to get_related_cpus() in devlib to reflect
the cpufreq nomenclature. This commit makes corresponding changes in WA.
=> cpufreq: raname get_domain_cpus

wlauto/common/linux/device.py
Previously, a AttributeError has been raised. This causes issues when
attempting to access some properties that rely on invoking commands on
the device. The error would get swallowed up in Python attribute
resolution machinery, resulting in an error claiming a missing
attribute.
For example, for AndroidDevice, "abi" is a property that internally
calls getprop(), which executes on the device, and thus requires a
connection. If attempting to access device.abi before device.connect()
has been invoked, the following sequence takes place
1. Caller tries to access attribute "abi" of device, which resolves to
the device.abi property defined in the class.
2. device.abi calls device.getprop()
3. ...which calls device.execute()
4. ...which calls device._check_ready()
5. device._check_ready() raises …
=> Device: raise RuntimeError in _check_ready

wlauto/utils/types.py
The overridden get method was incorrectly using __getitem__() when decoding the
data instead of get().
=> Types: Fix parameter dict get method

wlauto/commands/record.py, wlauto/common/android/workload.py, wlauto/common/linux/device.py, wlauto/common/linux/workload.py, wlauto/resource_getters/standard.py
Moved the ReventWorkload class to the Linux folder with new features (see 'revent' workload below) and it has now instead been sub-classed in the Android folder. There have been no functional changes as of yet to the Android version, but the possibility exists for their implementation and is detailed in the comments.
Introduced a new 'revent' workload to playback simple revent recordings, for use with instrumentation. The possibility to specify a .close file (which runs during teardown) as well as the existent .setup revent file has been added. It is also now possible to run the workload with 'idle' set to True in order to simply wait for a specified amount of time whilst still recording results instead of running the .run revent file, whilst still being able to run .setup and .close …
=> Revent integrated

wlauto/utils/revent.py
Previously the try clause worked to catch StopIteration exceptions correctly,
however upon catching the exception, another statment which set self._duration
to (last.time - first.time) was being run regardless, which defeated the point
of the try clause.
This has been fixed by introducing an else clause to contain said statement.
=> revent.py: Fix handling of zero-event files

wlauto/workloads/spec2000/__init__.py
spec2000 expects binaries to be optimised for particular cores and uses
Device's core_names to figure out which cores the benchmark should run
on.
There is one special case, which is "generic", which is not optimised
for a particular uarch. cpumask for this was resolved the same way,
failing the lookup, resulting in the invalid mask 0x0.
To fix this, "generic" is now handled by specifying the mask for all
available CPUs.
=> spec2000: fix cpumask for generic

wlauto/utils/ipython.py
nbconvert has been split into a separate package and is installed as a
dependency for Jupyter rather than IPython. Add a proper import guard
to prevent issues for those that don't need ipython_converter
functionality, and set the appropriate error message for those that do.
=> utils/ipython: handle nbconvert import

wa/framework/workload.py
This currently raises an error undonditionally when self.package is set, fix the
indentation so it only does that if it isn't installed on the target.
=> framework/workload: Fix resolve_packge_from_target

wlauto/common/android/workload.py, wlauto/workloads/applaunch/__init__.py
applaunch  users the UI automation of the guest workload to detect
launch completion. However, the guest's automaiton apk is pushed to the
target and loaded via DexLoader; it is never actually installed;
therefore, it should not be uninstalled when running guest's teardown.
=> applaunch: do not attempt to uninstall uiauto apk

wa/__init__.py
This is to enable some workloads that are currently out-of-tree.
=> wa: Add ApkWorkload to default imports

wa/instrumentation/trace-cmd.py
Due to the nature of modern Android devices, in order to usefully
interpret the power* events, you more and more often need to know the
kernel's view of temperature too. Therefore I think enabling the
thermal event group by default makes sense.
=> trace-cmd: Enable thermal trace events by default

wa/framework/configuration/core.py, wa/framework/execution.py, wa/framework/workload.py, wa/workloads/geekbench/__init__.py
Some workloads, such as Geekbench, may phone home and report data about the
device they are running on. This poses a risk for users that are testing on
unreleased or otherwise confidential devices - perhaps they use a standard
agenda to run a large battery of tests, in which case they may forget to disable
these dangerous workloads.
This provides a mechanism to prevent running those workloads from running by
setting allow_phone_home=False in the user configuration.
=> Add feature to mark workloads unsafe for confidential devices 

wa/workloads/youtube_playback/__init__.py
This is a very simple workload that just aims to allow collecting
instrumentation data on purely the video decoding aspect of Youtube.
=> youtube_playback: Add youtube_playback workload

wa/framework/target/runtime_parameter_manager.py
Runtime param names from config were matched against names available on
for the target using an overly-loose regex that resulted in the wrong
config point being returned.
Use caseless_string matching instead.
=> framework/target: fix runtime param name resolution

wa/workloads/geekbench/__init__.py
Seem I cherry-picked the geekbench workload from my WIP branch
without testing properly, and missed a fixup commit. Here's the
content of that commit, which fixes some missing updates from WA2 ->
WA3 APIs.
=> geekbench: Fix use of WA3 APIs

wa/framework/configuration/plugin_cache.py
Currently if you get confused and write a config with something like:
```
energy_measurement:
acme_cape
```
Then you get an error when we try to 'iteritems' on the value
'acme_cape'. Instead, explicitly check for this case.
=> PluginCache: Improve error message for ill-formed plugin config

wa/instrumentation/energy_measurement.py
Devlib's get_data API can return None when something goes wrong -
this currently results in us attempting to add a non-existent
artifact.
To avoid this confusion, check and use the return value from
get_data, instead of assuming that it will write data to its
'outfile' parameter.
=> energy_measurement: Check for failure of Instrument::get_data

wa/instrumentation/energy_measurement.py
Where backends have the capability to collect from multiple devlib
Instruments, EnergyMeasurement currently appends 'device' keys to the
names of metrics reported by those Instruments. Where multiple
Instruments are indeed used, it then sums up equivalent metrics to
produce the 'normal' metric without the 'device' keys
appended.
E.g. If you have two ACME 'devices' enabled you will get something
like
'device_total_energy_iio:device0' and
'device_total_energy_iio:device1', which will be summed to produce
'device_total_energy'.
However when only one Instrument is actually instantiated, this is
not needed and not done. Therefore just directly produce the metric
with the name originally given by devlib (i.e. in the example,
'device_total_energy').
=> energy_measurement: Ensure 'standard' energy metrics are produced

wa/instrumentation/hwmon.py
For some reason I didn't look at the WA2 instrument until afer I
wrote this, so it's different in how it handles 'before/after'
quantities (which I called 'momentary' in the code) - instead of
adding a 'mean' it just adds two separate metrics: one for before and
one for after. Personally I think this is more useful (esp. for
temperature) but if necessary I can revert to the old behaviour.
This also doesn't add the helpful classifier telling you the hwmon
device, because we don't have immediate access to that info from the
devlib Instrument. If necessary I'm sure it could be added later.
=> hwmon: Add hwmon instrument

wa/instrumentation/energy_measurement.py
The parameter support is untested as the defaults match what my system
does.
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
=> instrumentation: Add support for Devlib's monsoon instrument

wa/framework/configuration/core.py, wa/framework/execution.py
If a workload fails in `setup` or `run`, we continue with the run. This is an
attempt to have similar behaviour for failure in `initialize`.
If a workload fails in `initialize`, we SKIP all the jobs with the same
ID (i.e. same job spec) under the assumption that their `initialize` will fail
too.
-----
Marked this [RFC] because I don't really know if this is desirable behaviour (seems helpful to me, but maybe I've misunderstood the model), and I'm not sure if I've implemented it right (because Runner has to mutate ExecutionState by overwriting its job_queue)
=>  framework: Add bail_on_init_failure run configuration 

wa/workloads/dhrystone/__init__.py
Was invoking busybox in a hardcoded way, and was not using
self.target.busybox. Updated to use the correct version.
=> workloads/dhrystone: Fix taskset

wa/framework/resource.py
Update the File and Executable resource string representations to
actually include the words "file" and "executable" respectively to make
messages containing these representations (e.g. when a resource is not
found) clearer.
=> framework/resource: clearer file and exe strings

wa/framework/target/runtime_config.py
Some targets need more than 5 seconds to re-connect to a wifi network
after disabling airplane mode. Change the delay to 20 seconds to make
that more reliable.
=> framework/target: wait 20 sec for network to show up

wa/utils/android.py
Logcat entries are split on a ':' followed by a space so ensure this
is present in the line instead of just a ':'. Some devices have entires
without the trailing space causing an error.
=> Utils/Android: Fix missing space in check

dev_scripts/get_apk_versions, wlauto/utils/android.py
Some Linux distro provide android build-tools in packages, we should also try
to find 'aapt' in $PATH if it cannot be found in $ANDROID_HOME.
=> util/android, get_apk_versions: try to find 'aapt' in $PATH as well

wa/framework/configuration/core.py, wa/framework/configuration/plugin_cache.py, wa/framework/target/descriptor.py
- Add support for ConfigurationPoint aliases in configuration parsing.
- Add adb_name  alias fro AdbConnnection's device parameter for backwards
compatibility with WA2.
=> Add adb_name as an alias for AdbConnection param

wlauto/external/revent/revent.c
Add "static" qualifier to inline functions. This avoids linking errors
when compiling without -O flags. The "static" forces the inlining as
described here:
https://gcc.gnu.org/onlinedocs/gcc/Inline.html
=> external/revent: make inlines static

wa/workloads/dhrystone/src/dhrystone.c
Fix output when running for a specified number of loops (rather than
duration) and adding delay to threads. Previously, the output for the
last thread was not printed due to a missing check for a negative
duration.
=> workloads/dhrystone: fix run with num loops and delay

wa/framework/workload.py
Get pushed file basename to ensure the assets deployed path is correct.
=> framework/workload: Fix path of deployed asset

wa/framework/workload.py
On some devices an installed apk filepath can contain an '=' character
which was previously used to end the regex match. Now match with the
package name as well to ensure the file path is extracted correctly.
=> framework/workload: Fix incorrect regex matching apk filepath

wa/framework/target/runtime_parameter_manager.py
Fix the setting of runtime parameters when the casing of the parameter in
the agenda does not match the "canonical" casing.
To make the writing of agendas easier, the casing of the parameters is
supposed to be ignored. To achieve this, parameter names are converted to
caseless_string type before they are looked up.
caseless_string's do not work with dicts. Both __contains__ (used for
the "in" operator) and __getitem__ (used for the [] operator) implement
hash-based look up, and it is not possible to have a caseless_string
match against multiple hashes to cover the different casing
possibilities.
So instead, iterate over the items in parameters dict, comparing the
caseless_string name to the key, and returning the value if it matches.
=> framework/target: fix caseless runtime params

wa/workloads/exoplayer/__init__.py
To improve reproducibility of tests, it could help to ensure that the
same screen orientation is used on media playback.
This adds a new workload parameter which allows to ensore a LANDSCAPE
mode, which can be useful to better represent video playback scenarios.
When not enforced by the agenda, we enforce a PORTRAIT orientation.
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>
=> Exoplayer: Add support for Landscape mode

wa/framework/configuration/core.py
Add missing 's' for alias name.
=> configuration/core: Fix alias for 'results_processors'

wlauto/resource_getters/standard.py
Previously `ExtensionAssetGetter` subclassed `DependencyFileGetter`,
commit 6e7087ee88b34af453e20f0d8dda95438c72a8fb changed its
functionality to use a cached location instead of the local resource
location. This commit changes the `ExtensionAssetGetter` to subclass
`EnvironmentDependencyGetter` so it checks the local resource location
again.
=> resource_getters: Change ExtensionAssetGetter to look in local env

wlauto/common/android/resources.py, wlauto/common/android/workload.py, wlauto/resource_getters/standard.py
Allows distinguishing between apks based on the package name specified
in the workload.
=> resource_getters: Add support for matching apks via package name

wlauto/instrumentation/fps/__init__.py
Ensure the view name is passed in quotes to allow for views containing
spaces.
=> instrumentation/fps: Allow measuring of views containing spaces

wlauto/instrumentation/fps/__init__.py
When parsing the SurfaceFlinger list output spaces were used as
separators. Some view names have spaces enclosed.
This would lead to views with spaces in their names not being correctly
detected and as a consequence the fps stats not collected.
=> instrumentation/fps: Fix spaces in SurfaceFlinger.

wa/framework/output_processor.py
Output processor names are converted to identifiers when they are
loaded. Ensure the same thing happens when looking up installed output
processors with get_output_processor().
=> framework/output_processor: fix get_output_processor()

wa/framework/configuration/core.py
Add support for loading plugins from packages that register themselves
with WA by writing their names into $WA_USER_DIRECTORY/packages.
This is functionality that existed in WA2 and was omitted in WA3 until
now.
=> framework/config: load plugins from extra packages

wa/workloads/exoplayer/__init__.py
Do not attempt to reset rotation in teardown if target did not specify
it before workload execution.
=> workloads/exoplayer: handle no orig rotation

wlauto/common/android/workload.py
In addition to `GameWorkloads` some benchmarks also download additional
data upon initialisation. Moving this parameter to the `ApkWorkload`
parent class allows all APK based workloads to indicate that their data
should not be cleared prior to running the workload.
=> android/workload: Move parameter from GameWorkload to ApkWorkload Class

wa/commands/create.py
Move the iterations parameter into the general `config` section so the
`global` section can be removed.
=> commands/create: Remove global section of generated agenda

wa/framework/workload.py
Make the error message reported when no matching Android app package
could be found more useful by including the workload name, and, if
applicable, sought version.
=> framework/workload: make "no matching package" message more useful

wa/framework/workload.py
Fix an issue introduced by commit 42fb3eb
framework/workload: make "no matching package" message more useful
PackageHandler was incorrectly passing self.name into the error message
instead of self.owner.name.
=> framework/workload: fix "no matching package" error

wa/workloads/rt_app/__init__.py
Change "pull_file" to "pull" when exacting results. "pull_file" was WA2
API which somehow got missed.
=> workloads/rt-app: fix

setup.py
For some reason the automatic install of pandas will fail compilation
due to an issue with numpy. A workaround for this issue is to specify
numpy in `setup_requires` as mentioned in https://github.com/numpy/numpy/issues/2434
=> setup.py: Add work around for installing pandas

wa/workloads/hackbench/__init__.py
Set target_binary as a class, rather than instance, attribute. This
happens only only once per run, and setting it as instance attribute the
first time, makes it unavailable for subsequent instances of the same
workload.
=> workloads/hackbench: fix target_binary

wa/framework/configuration/plugin_cache.py
Add a special error for finding `global` entry in configuration to
provide a more helpful error message.
=> configuration/plugin_cache: Add specific error for `global` in config

wa/framework/execution.py
Missed some "output" references in the previous commit.
=> framework/execution: end_run() fix part 2

wa/workloads/rt_app/__init__.py
We redirect stderr to stdout for rt-app to allow us to capture the
output. Also remove requirement for root.
=> workload: rt-app fixes

wa/__init__.py, wa/framework/entrypoint.py, wa/framework/exception.py, wa/framework/execution.py, wa/framework/instrument.py, wa/framework/job.py, wa/framework/output.py, wa/framework/signal.py, wa/framework/target/descriptor.py, wa/framework/target/manager.py, wa/utils/log.py, wa/workloads/rt_app/__init__.py
This pull request contains some fixes for how WA behaves when the usual
execution flow is interrupted by an unusual event. Specifically,
- Fix the behavior on CTRL-C. Previously, hitting CTRL-C once would interrupt
execution of the current job but would then move onto the next one, requiring
mashing it repeatedly for the run to terminate. Now, hitting once will
interrupt the current job, and finalize the run, skipping the subsequent
jobs (note: if the job has reached the "run" stage, there would still be an
attempt to process the output and tear it down).
- Implement the handling of unresponsive targets. A hard reset will be
performed, if possible, or the run will be terminated, if not.
As a "bonus", the pull request also contains enhancements to the target
description APIs intended to …
=> Abnormal execution conditions fixes and enhancemens

extras/Dockerfile
With this commit we add a Dockerfile which can be used to create a
Docker image for running WA and devlib. Users are able to use this
image in a Docker container to run workloads on devices, without
requiring WA on their host systems. Please be aware that udev rules
must still be correctly setup on the host.
NOTE: This Dockerfile will accept the Android SDK licenses
automatically.
=> Docker: Add a Dockerfile for running WA

wa/output_processors/sqlite.py
This is WA2 sqlite result processor ported to WA3 output processor API.
It is schema-compatible with the WA2 version (in fact, there are *no*
schema changes).
Note: There is a medium-term goal of adding a more generic SQL database
exporter with a more complete schema sitting on top of something like
sqlalchemy to make it agnostic of DBMS implementations. At point, this
will likely be deprecated.
=> output_processors: add sqlite processor

wa/workloads/exoplayer/__init__.py
Split the desired format outside of for loop as this may not be
executed.
=> workloads/exoplayer: Fix splitting of format in incorrect location

wa/framework/workload.py
Fix an issue where AndroidWorkload.pull_apk would sometimes get the
wrong package if the desired package name is a substring of another
package name. Rather than using a regex to match the package name, use
the new get_package_info method to match the name exactly.
Replies on https://github.com/ARM-software/devlib/pull/250
=> fw/workload: Fix installed apk info

wa/utils/doc.py
Now displays all available local and global aliases when generating the
rst for a parameter.
=> utils/doc: Adds support for showing aliases when formatting parameters

wa/workloads/dhrystone/__init__.py
Only try to process output from the workload if it is available.
=> workloads/dhrystone: Fix crash if workload did not complete

wa/instruments/energy_measurement.py
Arm Energy Probe with arm_probe has been recently added in devlib's instrument.
Add the arm_energy_probe in the WA list of Energy measurement instruments
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
=> Add arm energy probe instrument

wlauto/workloads/recentfling/__init__.py
Not all devices are supported by recentfling, but there is usually a
device that is supported and has a similar screensize.  Let the
recentfling workload specify the device to let us run it on more
devices.
=> recentfling: Add the ability to specify the device_name

wa/framework/target/assistant.py
Adds missing `disable_selinux` parameter to the chromeos assistant and
pass it to the android assistant if applicable.
=> target/chromeosassistant: Fix missing disable_selinux parameter

wa/instruments/energy_measurement.py
something wrong has happened when preparing the patch to add
arm-probe AEP support.
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
=> aep: fix variable typo

wa/framework/output.py
Add a property that gives augmentations used by all jobs in the run to
RunOutput.
=> fw/output: add augmentations to RunOutput

wa/instruments/energy_measurement.py
resistor_values is an array of float and not int as the shunt resistors
are most of the time lower than 1 Ohm.
With kind=list_of_ints, all resistor values are rounded to 0.
Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>
=> daq: fix resistor_values parameters list

wa/workloads/manual/__init__.py
Port manual workload from WA2. This workload allows using WA to
configure and instrument the target, while letting the user perform
arbitrary actions in place of running a fixed workload.
=> workloads: Add manual workload

wa/framework/getters.py
If the http getter is used but a connection is not avalible, when
attempting to fetch the resource index an error will be raised. Now we
ignore the error allowing for the remaining getters to be used.
=> framework/getters: Ignore connection errors with HTTP getter

wa/commands/process.py
commands/process create initial version
Add process command to run output processors over data produced by
a previous run.
Default processing is to skip the processors that were used during
the run and to process the specified directory only. Options to
use additional processors, force reprocessing and allow a directory
walk to discover additional output directories.
=> @Rahlubenru

wa/framework/configuration/core.py
As part of finalizing a job spec, ensure all *_parameters are
obj_dict's.
=> fw/config: ensure params are obj_dict's

extras/Dockerfile
If one wishes to use the docker container with a TTY, then one must
explicitly mount it into the container when starting it. A note
conveying this has been added to the Dockerfile.
=> docker: Add note on how to use TTY

wa/framework/configuration/parsers.py
If WA is ran without any workloads being specified previously an index
Error was thrown, now check to see if jobs have been generated and if
not provide a more helpful error message.
=> config/execution: Raise better error if no workloads specified.

wlauto/utils/ssh.py
Ensure that the terminal window size is set to 500x200, if not long
commands (prompt + command > 80 chars) will fail because the pexpect
search to match the command string in order to get the result and the
command is wrapped to first 80 chars.
For example, when check a file and executes:
...
if [ -f '/sys/kernel/debug/sched_features' ]; then echo 1; else echo 0; fi
...
File
\"/usr/local/lib/python2.7/dist-packages/wlauto/common/linux/device.py\",
line 228, in get_properties
if self.is_file(propfile):
File
\"/usr/local/lib/python2.7/dist-packages/wlauto/common/linux/device.py\",
line 215, in is_file
return boolean(output.split()[-1])  # pylint: disable=maybe-no-member
IndexError(list index out of range)
...
In order to fix this scenario enables checkwinsize in the shell and use
stty to …
=> wlauto/utils/ssh.py: Fix set terminal window size

wa/instruments/screencap.py
Add an instrument which wraps the devlib screencapture poller, which
allows us to capture a screenshot from the device every `period`. The
`period` is configurable based on the user requirements.
All captured screenshots are named according to the timestamp on the
device, and are placed into an output directory (screen-capture)
within the job directory.
Note, this depends on https://github.com/ARM-software/devlib/pull/261
=> instruments: Add screencap

wa/commands/show.py
Ensure that plugin names are converted to identifiers when searching for
plugins.
=> commands/show: Add missing identifiers

doc/source/user_reference/configuration.rst, wa/commands/run.py, wa/framework/configuration/core.py, wa/framework/configuration/tree.py, wa/framework/entrypoint.py, wa/framework/plugin.py, wa/framework/resource.py, wa/utils/log.py
- Buffer early log records before a log file becomes available, so that they are
not lost.
- Add `indentcontext` to remove the need for `try`/`finally` guards for ensuring dedenting.
- Remove superfluous "Skipping..." entries from `pluginloader` logging.
=> Do not lose early logging

wa/commands/run.py
This was moved to wa/framework/entrypoint.py but was kept here due to a
botched merge during a rebase.
=> command/run: remove version/args logging.

wa/framework/execution.py, wa/utils/misc.py
- Use indentcontext inside initialize_run to make sure log level
is dedented on error.
- Ensure Executor postamble always runs, event if runner errors.
- Fix format_duration() to handle sub-second timedeltas.
=> fw/execution: handle error on run initialize

wa/__init__.py, wa/framework/configuration/plugin_cache.py, wa/framework/plugin.py
Workload aliases were broken at some point. When creating job specs, the
defaults for a plugin are set by the plugin_cache. This ensures that the
complete configuration is present in the meta data. This is happening
before the plugin alias is resolved on creation, and so the alias's defaults
were being overwritten by the unaliased plugin defaults in the job spec.
To avoid this, set the correct  defaults when creating the job spec.
=> Fix workload aliases.

wa/framework/job.py
Add "with indentcontext():" to Job stages that were missing them.
=> fw/job: add missing log indents

doc/requirements.txt
Readthedocs has updated their default sphinx version to be
incompatible with how our api is generated so force read the docs to use
the latest known working version (1.6.5)
=> doc/requirements: Force sphinx to be an older version.

wa/framework/execution.py
If strict=False, resolver.get_resource will return None, rather
than raising NotFoundError. Do not attempt to record the md5 hash in
that case.
=> fw/execution: fix get_resource with strict=False

wa/instruments/delay.py
Add space between a note admonition and the preceding paragraph.
=> doc/delay: fix warning.

wa/framework/entrypoint.py
In a previous commit we filtered parameters so that '-h' is never passed
to 'parse_known_commands' to ensure our own custom help message is displayed,
now also filter for '--help' for the same reason.
=> fw/entrypoint: Fix help information for '--help' argument

wa/utils/serializer.py
Fix a regression introduced with Python 3 port -- JSON deserializer
should check for basestring rather than str when deciding whether to try
to decode a custom type.
=> utils/serializer: fix level deserialization

wa/utils/serializer.py
Was replaced with str during Python 3 porting.
=> utils/serializer: add basestring to POD_TYPES

doc/source/instrument_method_map.template, wa/__init__.py, wa/framework/execution.py, wa/framework/instrument.py, wa/framework/signal.py, wa/framework/target/manager.py
Call self.reboot() instead of self.target.reboot() when attempting a
reset for unresponsive targets inside TargetManager, in order to ensure
that appropriate signals are dispatched.
=> fw/target: fix signals reboot on unresponsive

wa/framework/entrypoint.py
Python 3 has changed the behavior of subparsers so that they are no
longer mandatory by default. As a result, executing just "wa" under
Python 3 results in a random error, rather than a help message.
Fix this by making the subparsers mandatory.
=> fw/entrypoint: make command mandatory for Python 3

wa/instruments/serialmon.py
This instrument will log serial traffic to a file. The idea is to
assist with debugging development boards, as otherwise there is a
chance that crash reports, for example, are lost when the device is
reset by WA.
It logs the pre-run and post-run traffic to preamble_serial.log and
postamble_serial.log , respectively, in the top-level output
directory. Serial logs for each workload are stored in the appropriate
workload directory as serial.log.
As we are tying up the serial port, we stop the logging when the
device is reset to allow board such as the Arm Juno to be reset via
the serial connection.
Please note that this is dependent on https://github.com/ARM-software/devlib/pull/280
=> instruments/serialmon: Add an instrument to monitor serial traffic

wa/framework/command.py
Make subcommands required arguments in the ComplexCommand class, which
is used by the 'wa create' command.
=> framework/command: Fix subparsers in Python3

wa/framework/version.py
Add an stderr argument to redirect errors ('fatal not a git repository'
is the most common) to PIPE so that errors do not output to STDOUT.
=> framework/version: Redirect git stderr output

wa/utils/serializer.py
The ValueError does not given enough information in the case of an empty file
extension. Add a special case to handle files with no extension and
prompt the user.
=> utils/serializer: Handle empty file extensions

wa/commands/revent.py
Add a dummy method to the LightContext to satisfy the API as we
do not record metadata when performing revent recordings.
=> commands/revent: Add dummy method to LightContext

wa/framework/output.py
Add wa and devlib versions to RunOutput's metadata on creation. They
already get logged, but this will make them readily accessible to
scripts and output processors.
=> fw/output: record wa/devlib version in output

wa/workloads/chrome/__init__.py, wa/workloads/gmail/__init__.py
Correct setting of attribute `clean_assets` to `cleanup_assets`
=> workloads: Fix incorrect attribute name

wa/workloads/chrome/__init__.py
- Escape asterisk (otherwise, it is interpreted as "open emphasis")
- Use monospace formatting for paths.
- Trim to 79 columns wide
=> workloads/chrome: fix docs

wa/framework/configuration/core.py
Previously if a path for the `user_directory` was specified using `~`
this would not be expanded causing issues due to incorrect path joining.
=> fw/core: Allow for a `user_directory` to be specified using `~`

wa/workloads/apache.py
urllib2 does not exist in Python 3, and its methods have been moved into
urllib.request. Use future library to create aliases that work across
both 2 and 3.
=> workloads/apache: fix for Python 3

.gitignore
Update the location of the instrument method map with the new structure
for the documentation.
=> gitignore: Update to reflect new doc structure

wa/framework/version.py
When installing from source WA attempts to include the commit ID in the
version of the installed pacakge however this caused issues with package
managers like pip. PEP440 specifies that local identifiers must be in the
form `<public version identifier>[+<localversion label>]` so update the
version to conform.
https://www.python.org/dev/peps/pep-0440/#local-version-identifiers
=> fw/version: Change format of version to conform with PEP440

wa/utils/misc.py
- Lengthen timeout for `gemm` and `conv` tests of `deepbench` to be the same as for sparse test. 
- Consider headers when calculating column widths inside `write_table`. This will ensure proper alignment in cases where the column header is wider than any of the column values.
=> Misc fixes

doc/source/api/output.rst
Add a reference to the processing WA output how-to inside the output API
docs.
=> doc: ouput api: add reference to how-to

wa/workloads/mongoperf/__init__.py
Add a workload that runs mongoperf benchmark that measures I/O
performance on a MongoDB server. This workload assumes that mongoperf
is already installed.
=> workloads: add mongoperf

wa/workloads/mongoperf/__init__.py
Mongoperf currently has a non-ASCII character in the file that causes a failure.
This commit rewords the description to remove the incriminating character.
=> workloads: fix mongoperf

wa/workloads/jankbench/__init__.py
Instead of using the os to determine whether the screen state should
be checked, use target flag to see if running inside a container.
Dependant on https://github.com/ARM-software/devlib/pull/296
=> workloads/jankbench: Update to check if running in a container.

wa/framework/workload.py
Remove unused ``platform`` attributes and add ``supported_platforms``
along with check so that workloads can fail early when attempting to run
on an incorrect platform.
=> framework/workload: Add check for platform

tests/test_signal.py
Set signal logger level to CRITICAL to prevent it from spewing out
log message on the console for expected errors during tests.
=> tests: quieten signal logger

.travis.yml
Currently will execute the unittests using nose2 for python versions
2.7, 3.4 and 3.6
=> Travis: Add initial version of travis configuration file

wa/framework/output.py
Update the internal _combined_config object with the one that
has been written to ensure that the serialized and run time states are
the same.
=> fw/output: update internal state on write_config()

wa/framework/version.py
Check that the resulting output inside get_commit() is a str before
attempting to decode it when running on Python 3.
=>  utils/version: do not decode bytes

tests/test_utils.py, wa/utils/types.py
- Change how "source" and "dest" are handled inside merge() to be more
sane and less confusing, ensuring that disabling toggles are merged
correctly.
- Do not drop disabling values during merge, to ensure that merging
is a transitive operation.
- Add unit tests for the above fixes.
=> utils/toggle_set: fix merge behavior

wa/framework/target/info.py
Add target's system_id to TargetInfo. This ID is intended to be unique
of the combination of hardware and software on the target.
=> fw/target: add system_id to TargetInfo

wa/framework/configuration/core.py, wa/framework/host.py, wa/framework/target/info.py, wa/framework/target/manager.py
Use the newly-added system_id to cache TargetInfo objects. Attempt to retrieve
them from cache before querying target, in order to speed up execution.
On my setup, this reduced execution time for a  single dhrystone run on an
SSH-connected target from 49s to 35s, resulting in a speed up of 14s, or 29%.
=> Cache TargetInfo

.travis.yml
Force version 1.9.2 of pylint to be used rather than 2.0.0. Currently
there appears to be issues raising errors that are explicitly ignored.
=> travis: Force version 1.9.2 of pylint to be used

wa/framework/configuration/parsers.py
Ensure that a plug-ins config entry is converted to an identifier before being
stored in the PluginCache so that the relevant configuration can be
retrieved appropriately. For example this allows for both 'trace-cmd' and
'trace_cmd' to be used as config entries to provide configuration for the
'trace-cmd' plugin.
=> fw/parsers: Ensure plug-in names are converted to an identifier

wa/instruments/trace_cmd.py
If reporting on the target the extracted trace data file was not
defined, now locate the file correctly.
=> instruments/trace_cmd: Fix reporting on target

wa/framework/configuration/execution.py
Make sure that when retrieving plugin information from the plugin
cache the name is converted to an identifier first.
=> fw/execution: Ensure that identifiers are used when retrieving plugins.

wa/workloads/pcmark/__init__.py
Ensure that the results file is decoded when using python3.
=> workloads/pcmark: Fix reading results in python3

doc/source/developer_information/developer_guide/writing_plugins.rst, wa/commands/process.py, wa/framework/execution.py, wa/framework/output_processor.py, wa/output_processors/cpustates.py, wa/output_processors/csvproc.py, wa/output_processors/sqlite.py, wa/output_processors/targz.py
Expose the context to the initialize and finalize functions for Output
Processors. This was found to be necessary for the upcoming PostgreSQL
Output Processor.
=> Expose context in OP initialize and finalize

wa/framework/instrument.py
The Python2 inspect module does not contain the `getfullargspec` method so call
the appropriate method depending on Python version.
=> fw/instrument: Fix compatibility with Python2

doc/source/user_information/how_tos/agenda.rst, wa/framework/configuration/core.py, wa/framework/configuration/parsers.py, wa/framework/configuration/tree.py
Now allows for specifying a `group` value for each section which will
cross product the sections within that group with the sections in each
other group. Additionally classifiers will automatically be added to
each job spec with the relevant group information.
=> configuration: Add support for section groups

wa/utils/revent.py
- change magic string literal to a b'' string so that the comparison
works in python 3
- expand timestamp tuples (struct.unpack always returns a tuple) before
attempting to cast to float.
=> utils/revent: recording parser fixes

wa/workloads/jankbench/__init__.py
Previously the LogcatRunMonitor left the logcat process running in the
background causing issues with concurrent accesses. Now ensure the thread
terminates correctly.
=> workloads/jankbench: Ensure logcat monitor thread is terminated

wa/tools/revent/revent.c
- force cast start/end timestamps to uint64_t to correct recording format issue on 32bit devices (i.e. 4 bytes timespec tv_sec written on 8 bytes memory slot)
=> tools/revent: recording timestamp fix

wa/framework/workload.py, wa/utils/postgres_convert.py, wa/workloads/gfxbench/__init__.py
Allow specifying that the packages data should not be cleared
before starting a workload. This is useful for benchmark apps that
otherwise need their assets redeploying each time.
=> fw/workload: Add parameter to control if package data should be cleared.

wa/commands/process.py
Ensure that that ProcessContext is initialized before attempting to
initialize any of the output processors.
=> commands/process: Fix initialization of ProcessContext ordering

wa/framework/output.py
Explicitly convert the passed message into a string as this is expected when
generating a event summary, otherwise splitting can fail.
=> fw/output: Ensure that `Event` message is converted to a string

wa/output_processors/postgresql.py
When verifying the database schema the connection instead of a cursor
should be passed.
=> output_processors/postgres: Fix incorrect parameter

wa/commands/show.py
In commit bb282eb19c48b5770186d136e8a40c0573ef59b9 devlibs
`escape_double_quotes` method was retired in favour of the `pipes.quote`
method however this does not format correctly for this purpose therefore
revert back to the original escaping method.
=> commands/show: Revert quoting method switch

wa/framework/output.py, wa/utils/misc.py
Use a dict-like string representation for classifiers, rather than the
default OrderedDict one, which is a lot more verbose and difficult to
read.
=> fw/output: better classifiers format for metrics

wa/framework/workload.py
Allow for easy configuring of a view for a particular workload as this
can vary depending on the device which can be used when using certain
instruments for example `fps`.
=> fw/workload: Add a 'View' parameter to ApkWorkloads

wa/framework/target/info.py
The Devlib KernelConfig object was refactored in commit
https://github.com/ARM-software/devlib/commit/f65130b7c7ecccfe2006e40d2735eeb86639772b
therefore update the way KernelConfig objects are deserialized to reflect the new
implementation and provide a conversion for PODs.
=> fw/target/info: Fix for KernelConfig refactor

wa/output_processors/postgresql.py
In the case of no screen resolution being present ensure that a default
is used instead of `None`.
=> output_processors/postgresql: Add missing default

doc/source/faq.rst
Although WA supports automatic updating during parsing of a serialized
`kernel_config` from devlib, if the installed versions of WA and devlib
have become out of sync where WA has "updated" the old implementation it
will not attempt to update it again when devlib is later updated to use
the new implementation and therefore will not trigger the existing
checks that are in place.
=> docs/faq: Add entry about missing kernel config errors

wa/framework/resource.py
Update checking of attributes to allow for empty structures as they can
be set to empty lists etc. and therefore should not be checking if
explicitly `None`.
=> fw/resource: Fix attempting to match against empty values

wa/utils/serializer.py
When attempting to access the message of a exception check not only that
e.args is populated, but also that e.args[0] actually contains
something, before defaulting to str(e).
=> utils/serializer: fix error reporting for YAML

wa/utils/serializer.py
Change the way maps get processed by YAML constructor to support YAML
features, such as anchors, while still maintaining dict ordering.
=> utils/serializer: fix support for YAML anchors.

wa/workloads/geekbench/__init__.py
The workload could attempt to use the version attribute before it was
discovered to assess the workload activity causing an error however the
whole process can be simplified using newer discovery features.
=> workloads/geekbench: Clean up version handling

tests/test_agenda_parser.py, wa/utils/serializer.py
New fix for https://github.com/ARM-software/workload-automation/issues/973.
=> utils/serializser: Re-fix support for YAML anchors

wa/framework/workload.py, wa/workloads/uibench/__init__.py
Add support for Android's UIBench (AOSP - [`frameworks/base/tests/UIBench`](https://github.com/aosp-mirror/platform_frameworks_base/tree/master/tests/UiBench)) suite of tests as a WA workload.
Please note that this is based on ARM-software/devlib#357.
=> Workloads: Add support for UIBench

doc/build_instrument_method_map.py, doc/build_plugin_docs.py
Patch to allow building the documentation under Python 3.x (should still work under 2.6+).
Fix an incorrect function name in a script.
Fix `doc/build_plugin_docs.py` according to Pylint and the configuration file in this repository.
=> Port scripts for doc generation to Py3 & Pylint fixes

wa/framework/configuration/execution.py
If no jobs have been generated that are available for running then WA
will crash when trying to access the job queue. Add an explicit check to
ensure that a sensible error is raised in this case, for example if
attempting to run a specific job ID that is not found.
=> fw/config/execution: Raise error if no jobs are available for running

wa/__init__.py, wa/framework/workload.py, wa/workloads/uibenchjanktests/__init__.py
This workload uses `am instrument` to launch the official AOSP automation of UIBench (see the existing WA workload for that one).
=> Add a workload for UIBench JankTests

wa/framework/workload.py, wa/workloads/dhrystone/__init__.py, wa/workloads/hackbench/__init__.py, wa/workloads/hwuitest/__init__.py, wa/workloads/lmbench/__init__.py, wa/workloads/meabo/__init__.py, wa/workloads/memcpy/__init__.py, wa/workloads/openssl/__init__.py, wa/workloads/rt_app/__init__.py, wa/workloads/shellscript/__init__.py, wa/workloads/stress_ng/__init__.py, wa/workloads/sysbench/__init__.py
As per https://github.com/ARM-software/workload-automation/issues/643 for debugging purposes it would be useful to be able to disable the cleanup of workloads. 
Improve the usage of the existing `clean_up` parameter across workloads and add `uninstall` to the base `workload` class to allow the control of uninstalling all executables instead of just apk applications.
=> Teardown improvments

wa/framework/resource.py, wa/framework/workload.py, wa/utils/types.py, wa/workloads/geekbench/__init__.py
As per https://github.com/ARM-software/workload-automation/issues/627 WA2 supported specifying not only a particular version of an apk but also a maximum and minimum. Add the corresponding functionality to WA3 and also improve the existing version matching.
=> Max min version

setup.py
In the latest versions of panadas and numpy python2.7 support has been
dropped therefore restrict the maximum version of these packages.
=> setup.py: Set maximum package version for python2.7 support

doc/source/faq.rst, extras/Dockerfile, wa/framework/entrypoint.py
Motivating https://github.com/ARM-software/workload-automation/issues/982 we want to try and prevent encoding issues during operation therefore provide information to the user if their environment is not configured to support UTF-8.
=> Support checking of the default encoding

doc/source/api/output.rst, wa/commands/postgres_schemas/postgres_schema.sql, wa/commands/postgres_schemas/postgres_schema_update_v1.3.sql, wa/commands/schema_changelog.rst, wa/framework/output.py, wa/instruments/misc.py, wa/output_processors/postgresql.py, wa/utils/postgres.py
This set of commits allows for storing directories as an Artifact and implements the functionality of being transparently uploaded and retrieved from a database.
Items to note:
- Upon uploading artifacts to the database the directory will be compressed and stored as a `.tar.gz` file.
- Upon invocation of `get_artifact_path` the `.tar.gz` file will be streamed from the database and  extracted to a temporary location with the prefix `'wa_'` before returning the path of the newly extracted directory. It is currently left to the user to delete the folder once they are finished with it. 
- The naming scheme for the `SysfsExtractor` instrument artifacts is currently in the form `<path> [stage]` for example `/sys/devices/system/cpu [before]`.
=> Storing directories as Artifacts + Postgres Fixes

.readthedocs.yml
Provide configuration file for building the documentation. We need to
specify to use python3 explicitly.
=> Add ReadTheDocs configuration file

setup.py
Pandas versions 0.25+ requires Python 3.5.3 as a minimum so ensure that
an older version of pandas is installed for older versions of Python.
=> setup.py: Update pandas version restrictions

wa/instruments/energy_measurement.py
Forward the teardown method invocation to the instrument backend.
Related to https://github.com/ARM-software/devlib/pull/431
=> instrument/energy_measurement: Invoke teardown method for backends

wa/instruments/energy_measurement.py
Add a `keep_raw` parameter to control whether raw files should be
deleted during teardown.
Dependant on https://github.com/ARM-software/devlib/pull/431
=> instruments/energy_measurement: Add a `keep_raw` parameter

wa/commands/postgres_schemas/postgres_schema.sql, wa/commands/postgres_schemas/postgres_schema_update_v1.5.sql, wa/commands/schema_changelog.rst, wa/framework/target/info.py
- Fix upgrade of `TargetInfo` POD to v5.
- Change "hostid" field to Bigint to allow storing of larger ids.
=> Postgres OutputProcessor Fixes

wa/instruments/energy_measurement.py
The signature of `get_instruments` was missing the `keep_raw` parameter
so fix this and use it as part of the subsequent common invocation.
=> instruments/acme_cape: Fix missing parameter to `get_instruments`

pytest.ini, tests/data/extensions/devices/test_device.py, tests/test_exec_control.py, wa/utils/serializer.py, wa/utils/types.py
Fix warnings reported when running unit tests via pytest.
- Rename TestDevice to MockDevice, so that it is not interpreted as a
test case.
- Fix collections abstract base class imports.
- Add an ini file to ignore the same from "past".
=> tests: fix pytest warnings

wa/workloads/geekbench/__init__.py
There have been no UI changes to the application so simply adding the
new supported version to the list of accepted versions.
=> Geekbench: Adding 4.4.2 as a supported version

wa/utils/trace_cmd.py
re._pattern_type became re.Pattern in Python 3.
=> utils/trace_cmd: update for Python 3

wa/utils/cpustates.py
If idle state names for a cpu could not be discovered, use "idle[N]"
where N is the state number, instead of just making them all as
"unknown".
=> utils/cpustates: update idle state naming

wa/framework/getters.py
Use Executable.match() rather than just checking the path inside
get_from_location(); this allows for alternative matching semantics
(e.g. globbing) inside derived implementations.
=> fw/getters: update Executable resolution

wa/framework/target/manager.py, wa/utils/types.py
Allow for comparing which modules are installed on a Target when
additional module configuration is present.
=> Convert modules to a name only set 

doc/source/api/output.rst, wa/framework/execution.py, wa/framework/job.py, wa/framework/output.py
Add add_classifier() method to context. Allow plugins to add classifiers
to the current job, or the run as a whole. This will ensure that the new
classifiers are propagated to all relevant current and future artifacts
and metrics.
=> fw/exec: Add add_classifier() method

wa/framework/job.py
Now that classifiers may be added to the job during execution, its
classifiers dict should be unique to each job rather than just returning
them form spec (which may be shared between multiple jobs.)
=> fw/job: copy classifiers from the spec

wa/workloads/exoplayer/__init__.py
Android 10 appears to use a new format in logcat when displaying the
PlayerActivity. Update the regex to suport both formats.
=> workloads/exoplayer: Support Android 10

wa/framework/workload.py
Previously, when pulling an apk from the target to the host, the default
package name was used for both regular apks and test apks. This could
result in one package overwriting the other. To prevent this ensure
`TestPackages` have the "test_" prefixed to their filename.
=> fw/workload: Prefix `TestPackages` with "test_"

wa/framework/plugin.py, wa/framework/workload.py
Move cleanup_assets from Workload up into TargetedPlugin. This way,
Instruments may also utilize it if they deploy assets.
More generally, it makes sense for it to be inside TargetedPlugin, as
any plugin that interacts with the target may conceivably need to clean
up.
=> fw/plugin: move cleanup_assets to TargetedPlugin

wa/framework/instrument.py
Change Instrument to derive from TargetedPlugin rather than Plugin,
which it should have been all along.
=> fw/instrument: derive Instrument from TargetedPlugin

doc/source/developer_information/how_tos/adding_plugins.rst
Remove reference to `extract_results`, which does not exist for
Instruments (this only exists for Workloads.)
=> doc: fix Instrument documentation

tests/test_exec_control.py, wa/utils/exec_control.py
Add a decorator to run a method once for all instances that share the
value of the specified attribute.
=> util/exec_control: add once_per_attribute_value

tests/test_utils.py, wa/utils/types.py
Correctly handle the presence of both an element and its toggle in the
input, and handle them base on order, e.g.
toggle_set(['x', 'y', '~x']) --> {'y', '~x'}
toggle_set(['~x', 'y', 'x']) --> {'y', 'x'}
=> utils/types: fix toggle_set creation

wa/framework/target/descriptor.py
The majority of users will not find a benefit of the additional
check so make this parameter default to `False` instead.
=> target/descriptor: Make `strict_host_check` default to `False`

wa/utils/android.py, wa/workloads/aitutu/__init__.py, wa/workloads/androbench/__init__.py, wa/workloads/antutu/__init__.py, wa/workloads/benchmarkpi/__init__.py, wa/workloads/gfxbench/__init__.py, wa/workloads/jankbench/__init__.py, wa/workloads/motionmark/__init__.py, wa/workloads/speedometer/__init__.py, wa/workloads/vellamo/__init__.py
Some devices print non standard characters to logcat. If an error
occurs when parsing the output, replace the offending character instead
of raising an error.
=> logcat_parsing: Replace errors when decoding logcat output

wa/framework/getters.py, wa/framework/resource.py, wa/framework/target/info.py, wa/framework/workload.py, wa/instruments/misc.py, wa/utils/misc.py
As per https://github.com/ARM-software/workload-automation/issues/1076, when running multiple instances of WA there can be cases where there can be concurrent reads/writes to the same files causing conflicts.
Implement locking around pulling/parsing APK files and reading/writing `target_info` files.
=> Implement support for file locking 

wa/framework/target/descriptor.py
Make sure we only override parameters that are present in the current
config. This allows for connection parameters to be supplied for a
platform but only overridden if required for the connection.
=> descriptor: Fix overriding of parameters

wa/utils/misc.py
Use the original file path to create a lock file in the system temp
directory. This prevents issues where we are attempting to lock a file
where wa does not have permission to create new files.
=> utils/file_lock: Create lock files in system temp directory

wa/framework/configuration/core.py
Provide warning to user when attempting to set a depreciated
parameter instead of during validation and only raise the warning
if a value has been explicitly provided.
=> config/core: Fix handling of depreciated parameters

extras/Dockerfile
Instead of storing the environment variables in `.bashrc` store them
in `/home/wa/.wa_environment`. This allows for sourcing of this file
in non interactive environments.
=> Dockerfile: Update to store environment variables in separate file

doc/source/developer_information/developer_reference/plugins.rst, doc/source/user_information/installation.rst, doc/source/user_information/user_guide.rst, doc/source/user_information/user_reference/invocation.rst
- Remove references to Python 2.7 and update example paths
to Python3.
- Fix incorrect attribute name
=> docs/user_information: Fix references to Python 2.7

doc/build_instrument_method_map.py, doc/source/instrument_method_map.template
Correctly specify the decorator name that should be used to give an
instrument method appropriate priority when it's being invoked via
signal dispatch.
Previously, the table was listing the priority enum names in the column
that was labeled "decorator". Now both are shown and the distinction has
been made clearer.
=> doc: fix callback priority table

wa/workloads/jankbench/__init__.py
Pandas removed .ix as a way to iterate the index, .loc is the replacement
in most cases. Jankbench as a workload fails on a clean install due to
this call.
Replacing this works for me on a native install of Lisa with Ubuntu 20.04
Signed-off-by: Chris Redpath <chris.redpath@arm.com>
=> WA/Jankbench: Update Pandas function to remove deprecated .ix access

.travis.yml
The later versions of isort is not compatible with the version of
pylint we use so ensure we use a compatible version in the travis tests.
=> travis: Limit the maximum version of isort

tests/test_execution.py, tests/test_signal.py, wa/commands/report.py, wa/framework/execution.py, wa/framework/job.py, wa/framework/run.py, wa/framework/signal.py
- Test benches provided to track the serialisation of execution state to
the state file, and for the state of a retried job
- These were necessary to show that
a) Retried jobs did not have the correct status
b) Job status was not reflected promptly in the state file
- Serialisation was coupled with setting job status to prevent this,
and JobState was consolidated inside Job to aid status consistency.
- Added runstatus command for the monitoring of ongoing and
completed WA runs. 
- Fixed signal disconnection and added testcase
=> framework, tests, commands: Update state tracking

wa/framework/configuration/core.py, wa/framework/getters.py, wa/framework/resource.py, wa/framework/target/info.py, wa/framework/target/manager.py, wa/framework/workload.py, wa/instruments/misc.py, wa/utils/android.py, wa/utils/misc.py
- To prevent the requirement of parsing an APK file multiple times cache the information using its path and last modified time and keep a copy in memory. This should improve execution times when using large APK files and reduce contention when running with multiple instances of WA.
- To prevent long timeouts occurring during to file locking on both reads and writes implement and replace locking with atomic writes. While this may results in cache entries being overwritten, the amount of time used in duplicated retrievals will likely be saved with the prevention of stalls due to waiting to acquire the file lock.
- Generate the md5 hash of assets in chunks to prevent loading large files into memory at once.
Supersedes #1100
=> WIP: Code Optimisations 

wa/framework/target/assistant.py
As WA currently supports either a single logcat dump after each job,
or fixed rate polling of logcat, it is possible that the fixed size
logcat buffer wraps around and overwrites data between each dump or
poll. This data may be used by output processors that should be
notified of the loss.
This change allows the detection of buffer wrapping by inserting a
known log entry into the buffer, although it cannot say how much data
was lost, and only applies to the "main" logcat buffer.
If buffer wrap is detected, a warning is logged by WA.
Github Issue: https://github.com/ARM-software/workload-automation/issues/1114
=> framework/target: Add logcat buffer wrap detection

wa/commands/postgres_schemas/postgres_schema.sql, wa/commands/postgres_schemas/postgres_schema_update_v1.6.sql, wa/commands/schema_changelog.rst
Add cascading deletes to foreign keys as well as a rule to delete large
objects when artifacts are deleted.
Deleting a run entry should delete all dependent data of that run.
Issue: https://github.com/ARM-software/workload-automation/issues/1034
=> postgres_schemas: Add rules for cascading deletes

wa/framework/output.py
Avoid recursing into subdirectory of folders containing __meta, since
they are not of interest and recursing can take a very large amount of
time if there are lot of files, like if there is a sysfs dump.
On my setup, it makes  a ~1min run time turned into something negligible.
=> framework/output: Speedup discover_wa_outputs()

tests/test_execution.py, wa/framework/configuration/core.py, wa/framework/execution.py
Add a global configuration parameter ``bail_on_job_failure`` that
allows all remaining jobs in a run to be skipped should a job fail its
initial execution and its retries. This is by default disabled.
=> core,execution: Add run skipping on job failure

wa/framework/target/assistant.py, wa/framework/target/manager.py
Adds runtime config support for the android setting
``stay_on_while_plugged_in``.
Uses feature introduced [here](https://github.com/ARM-software/devlib/pull/505)
[Github Issue](https://github.com/ARM-software/workload-automation/issues/1106)
The pull request title is misleading, as since the initial
request the stay-on parameter is **no longer** a runtime
configuration, and is now a device configuration.
=> target/runtime_config: Add support for stay-on

wa/workloads/pcmark/__init__.py
When set to true, the data associated with the package will be cleared
(pm clear), before each workload run. The default value is "true" and therefore,
WA behavior remains the same. However, it gives a way of bypassing this
operation which is interesting for a workload such as PCMark, which wouldn't
have to download the benchmark data-set before each run. This download is
time-consuming and pollutes the benchmark instrumentation.
=> PCMark: do not clear on reset

wa/framework/target/runtime_config.py
Ensure there is a default iterable value in the case there is no
governor entry for a particular cpu.
=> fw/runtime_config: Fix case where no available gov for cpu

tests/test_config.py, wa/framework/configuration/core.py
Ensure that runtime and workload parameters specified across multiple
config files and the config section of the agenda are merged rather than
overwritten.
=> config/core: merge params from different files

wa/framework/target/descriptor.py
Adds connection parameters needed for WA to support file transfer polling.
``poll_transfers`` of type ``bool``, default ``True`` sets whether
transfers should be polled
``transfer_wait_no_poll`` controls the initial time in seconds that the
poller should wait for the transfer to complete before polling its
progress.
Works with changes implemented in [this pull request](https://github.com/ARM-software/devlib/pull/504)
=> target/descriptor: Add connection config for polls

wa/framework/target/descriptor.py, wa/framework/version.py
The WA default `sudo_cmd` is out of date compared to devlib.
Update the command template to include the latest version.
This enables sudo to read a password from stdin and fixes the password
prompt being included in a command output [1].
[1] https://github.com/ARM-software/devlib/pull/509
=> fw/descriptor: Update sudo_cmd default

wa/workloads/exoplayer/__init__.py, wa/workloads/rt_app/__init__.py
Remove explicit file transfer timeouts and rely on the polling mechanism if required.
=> Remove explicit file transfer timeouts

wa/utils/doc.py
Explicitly check for is `None` to determine if a default value is
not present or just a Falsey value.
=> utils/doc: Fix display of Falsey default parameters

wa/instruments/perf.py
With the perf instrument configured as:
perf:
perf_type: simpleperf
command: stat
optionstring: '-a --interval-only-values --csv'
WA fails to parse simpleperf's output:
INFO             Extracting reports from target...
ERROR            Error in instrument perf
ERROR              File "/work/workload_automation/workload-automation/wa/framework/instrument.py", line 272, in __call__
ERROR                self.callback(context)
ERROR              File "/work/workload_automation/workload-automation/wa/instruments/perf.py", line 142, in update_output
ERROR                self._process_simpleperf_output(context)
ERROR              File "/work/workload_automation/workload-automation/wa/instruments/perf.py", line 155, in _process_simpleperf_output
ERROR …
=> perf: correctly parse csv when using "--csv --interval-only-values"

wa/framework/version.py
On systems that do not have git installed WA will currently fail
to install with a FileNotFound Exception. If git is not present then
we will not have a commit hash so just ignore this error.
=> fw/version: Prevent installation failure on systems without git

wa/framework/target/runtime_config.py
If the device does not have the hoptplug module installed, avoid
unnecessary querying of the device to check the number of cpus which
can cause issues with some devices.
=> fw/rt_config: Avoid querying online cpus if hotplug disabled

wa/framework/job.py
Don't assume the first job iteration is already in the workload cache.
This may not always be the case, for example with the random execution
order a later iteration can be processed first.
Instead check to see if the job id is present or not.
=> fw/job: Fix workload cache check

doc/source/user_information/installation.rst
WA is called "wlauto" in pypi. "pip install wa" installs _workflow_
automation, a very different project.
=> docs/installation: Fix package name in pypi

wa/framework/target/info.py, wa/framework/version.py
Switch to using properties exposed by the target, allows for working around systems that cannot retrieve the hostname directly as per https://github.com/ARM-software/workload-automation/issues/1163 
Dependent on https://github.com/ARM-software/devlib/pull/538
=> Use newly exposed target properties for TargetInfo

doc/source/developer_information/how_tos/adding_plugins.rst
Fix typo reported in https://github.com/ARM-software/workload-automation/issues/1169
=> docs: Fix typo in variable name

wa/instruments/perf.py
devlib learnt to use report-sample in
ARM-software/devlib@fe2fe3ae0470 ("collector/perf: run simpleperf
report-sample in the target if requested").  Adapt the perf instrument
to use the new parameters of the PerfCollector.
=> perf: support report-sample

wa/workloads/pcmark/__init__.py
Add support for PCMark for Android version 3.
Use a 'version' Parameter to maintain support for v2.
=> workloads/pcmark: Add PCMark 3.0 support

doc/source/user_information/how_tos/agenda.rst
s/will/with/
as *with* all WA configuration, the more specific settings will take precedence over the less specific ones
=> docs: Fix typo

wa/instruments/perf.py
Currently, when processing the output of 'simpleperf stat', wa does not
skip the header and tries to process part of it as a number, leading
to type errors. This change skips the header (line starting with '#').
Furthermore, some events (e.g. cpu-clock or task-clock) include "(ms)"
in their count value and are floats instead of integers. Because of
this, when either of those is included, processing metrics fails due to
assuming every metric is an integer. Then another error happens when the
code tries to split the line on '(' assuming that there's only one set
of those around the percentage.
This change removes "(ms)" from the line
before it's processed and properly determines whether 'count' is an
integer or a float before attempting to convert it.
=> perf: Fix processing simpleperf stats

.github/workflows/main.yml, dev_scripts/pylint
The latest devlib master branch requires Python >=3.7 therefore
bump the python version used to run the CI tests.
=> ci: Bump the python version used for running tests

.readthedocs.yml
Bump the python version used to build the documentation
to prevent installation errors in the build environment.
=> docs/.readthedocs: Bump the python version

wa/framework/target/runtime_parameter_manager.py
This patch allows plugins to define their own runtime configurations. The primary motivation is to allow complex configurations that may be specific to a chip or device and have that configuration modifiable in sections to test sensitivity to those changes.
=> add support for loading runtime-config as a plugin

wa/framework/output.py, wa/instruments/misc.py, wa/utils/misc.py, wa/workloads/rt_app/__init__.py, wa/workloads/speedometer/__init__.py
Prevent potential directory path traversal attacks (see https://www.trellix.com/en-us/about/newsroom/stories/research/tarfile-exploiting-the-world.html)
This is an alternative to the automatically generated https://github.com/ARM-software/workload-automation/pull/1196/ reusing the same fix added to devlib in https://github.com/ARM-software/devlib/pull/608.
Note: This cannot be merged until we can also bump the devlib dependency in WA to keep the versions aligned.
=> Mitigate CVE-2007-4995

wa/framework/workload.py, wa/utils/android.py
In some workloads it is beneficial to be able to provide arguments when launching the required APK. Add a new `arpk_arguments` property to allow a workload to provide a dict of parameter names and values that should be used when launching the APK.
The python types of the parameters are used to determine the data type provided to the APK. Currently supported types are string, bool, int and float.
Required for https://github.com/ARM-software/workload-automation/pull/1208
=> fw/ApkWorkload: Allow workloads to provide apk arguments

wa/instruments/perf.py
The simpleperf included with Android 13 now does not show the percentage when no counter multiplexing took place. This causes the perf instrument to crash when processing the output. This fix checks whether the percentage exists before trying to extract it.
=> perf: Fix instrument for Android 13

wa/workloads/drarm/__init__.py
Add a workload for the Dr Arm demo app. Includes functionality for automatically pulling the ADPF FPS report file from the target if one was generated by the app.
=> drarm: Add DrArm workload

wa/workloads/uibenchjanktests/__init__.py
Rework the uibenchjanktests workload to allow specifying a list of subtests. The activity will be re-launched for each provided subtest. If none are specified, all available tests will be run in alphabetical order.
The workload output will now include metrics with their respective test names as classifiers.
Add a 'full' parameter to revert back to the old default 'full run' behaviour with restarts between subtests.
=> external.wa: uibenchjanktests: Rework to allow listing subtests

wa/workloads/drarm/__init__.py
Set the view parameter so that the FPS instrument can collect frame data from the workload.
=> worklads/drarm: Set view for FPS instrument

wa/framework/plugin.py
WA_PLUGIN_PATHS currently contains a list of filesystem paths to scan for plugins. This is appropriate for end-user plugins, but this is problematic for plugins distributed by a 3rd party, such as a plugin installed from PyPI.
In those cases, the path to the sources is unknown and typically depends on the specify Python version, local setup etc. What is constant is Python name of the package, e.g. "lisa.wa.plugins".
Extend the input allowed in WA_PLUGIN_PATHS by trying to load entries as a Python package name if:
* There is no filesystem path with that name
* The entry is a "relative path" (from an fs point of view)
=> fw/plugin: Try to load plugin paths as Python module name

wa/instruments/trace_cmd.py
Allow optionally setting the top level ftrace buffer size separately from the devlib buffer size. The parameter will be passed to the devlib FtraceCollector and take effect there.
=> instruments/trace_cmd: Allow setting top_buffer_size

wa/workloads/speedometer/__init__.py
Bromite is a fork of Chromium that's easily available for Android. Apart from small changes it works the same as Chromium and works with this speedometer workload. Add it to the 'package_names' list to allow using it as an option.
https://www.bromite.org/
=> workloads/speedometer: Add Bromite to package names

wa/framework/target/descriptor.py
Expose devlib's AdbConnection `adb_as_root` parameter in the target descriptor.
=> target/descriptor: Expose adb_as_root for AdbConnection

.readthedocs.yml, doc/requirements.txt, doc/source/conf.py
- Bump python version used when building documentation.
- `setuptools` is a deprecated installation method on RTD so switch to `pip`.
- Add additional dependency on devlib master branch as RTD env is not respecting dependency_links during installation.
- Bump copyright year.
=> docs: fix RTD build

wa/framework/workload.py
"--user <USER_ID>" (current user: 0) option is added to activity manager (am) command because of "Invalid userId" error. Tested with other benchmarks (geekbench) as well.
=> UIBenchJankTests: modification to support Android 14 version

doc/source/user_information/user_reference/runtime_parameters.rst, wa/framework/target/runtime_config.py
Introduce 'unlock_screen' option in order to help in automating Android tests by unlocking device screen automatically. Surely this works only if no passcode is set.
User can tell how to unlock screen (e.g., diagonal, vertical, ...) via 'unlock_screen' option. If unlocking the screen is undesired, then 'unlock_screen' should be set to empty string (e.g., '').
'unlock_screen' option is effective if 'screen_on' option is set to true. Its default value is 'vertical'. Since 'screen_on' is also true by default, the screen will be unlocked via 'vertical' direction in default settings.
Note that this patch depends on
https://github.com/ARM-software/devlib/pull/659 in devlib repo.
=> fw/rt_config: Add unlock_screen config option in runtime_parameters

dev_scripts/pylint_plugins.py, setup.py, wa/commands/revent.py, wa/commands/show.py, wa/framework/getters.py, wa/framework/instrument.py, wa/framework/plugin.py, wa/framework/version.py, wa/utils/misc.py, wa/utils/types.py, wa/workloads/jankbench/__init__.py, wa/workloads/meabo/__init__.py, wa/workloads/pcmark/__init__.py
Python 3.12 removed the "imp" module, so use importlib instead.
Also fix `load_class()` so that it works if the class is in a submodule.
Note that this PR was somewhat unit-tested (the new functions have been tested) but the integration in the rest of WA has not.
=> wa: Remove dependency on "imp" module and cleanup import mechanisms

wa/workloads/speedometer/__init__.py
Speedometer wasn't able to fetch the results when running on latest Chrome version. Regex search is updated to get the results. Now it's also searching for 'index="3"'. Tested with different devices to see index is always 3.
=> workloads/speedometer: Edit regex search to get the score

wa/workloads/speedometer/__init__.py
When speedometer is running on a Chrome package on Android 14, a pop-up window was showing on the screen. Chrome preferences file is modified to dismiss the window.
=> workloads/speedometer: Dismiss notification pop-up

doc/source/user_information/user_guide.rst, wa/framework/target/descriptor.py
devlib/AdbConnection class supports customizing ADB port number. Enable that feature in WA side.
=> target/descriptor: Support adb_port parameter

wa/workloads/speedometer/__init__.py
The regex pattern for extracting speedometer score causes these exceptions due to unescaped `\d` and `\/` sequences:
```
wa/workloads/speedometer/__init__.py:109: SyntaxWarning: invalid escape sequence '\d'
'(?:text|content-desc)="(?P<value>\d+.\d+)"[^>]*'
wa/workloads/speedometer/__init__.py:110: SyntaxWarning: invalid escape sequence '\/'
'(?(Z)|resource-id="result-number")[^>]*\/>'
```
Fix the problem via defining the regex pattern as raw string literal to properly escape backslashes.
=> workloads/speedometer: Fix SyntaxWarning exceptions in regex pattern

.github/workflows/main.yml, wa/commands/create.py, wa/utils/misc.py
Update CI to run with later python versions and update to align with latest available versions provided by github actions.
=> ci: Bump python versions

doc/source/user_information/user_guide.rst, doc/source/user_information/user_reference/agenda.rst, wa/instruments/trace_cmd.py
Implement tracing mode support (mainly for write-to-disk mode) in TraceCmdInstrument, enabling efficient collection of large trace datasets without encountering memory limitations.
This feature is particularly useful for scenarios requiring extensive trace data.
Additional changes:
- Replace hardcoded strings with corresponding string literals for improved maintainability.
=> instruments/trace_cmd: Add tracing mode support to TraceCmdInstrument()

wa/workloads/geekbench/__init__.py
Geekbench command-line build is added for Android. Geekbench apks allow to user to run the tests altogether. Using the command-line build, a single test or multiple tests can be specified.
=> workloads/geekbench: Add support for Geekbench command-line build

wa/framework/workload.py, wa/utils/revent.py, wa/workloads/honorofkings/__init__.py
- **framework: utils: Improve logging in revent replay related methods:**
Also fix typos around the modified lines.
- **workloads: Add support for Honor of Kings game:**
Introduce a new workload for automating match replays in Honor of Kings.
This workload leverages ApkReventWorkload to launch the game and play
back a specified replay file.
Allow customization through parameters:
- `activity`: Specifies the activity string of the game.
- `replay_file`: Designates the replay file to be uploaded.
The game can be replayed via `wa replay` command as well, but this
plugin makes data collection (`fps`, `trace-cmd` like augmentations)
a lot easier.
=> Add support for Honor of Kings game
